//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.03.06 at 08:47:27 AM PST 
//


package gov.noaa.pmel.oads.v_a0_2;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for base_variable_type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="base_variable_type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="datasetVarName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="variableType" type="{http://ncei.noaa.gov/oads_metadata}variable_type"/>
 *         &lt;element name="observationType" type="{http://ncei.noaa.gov/oads_metadata}observation_type"/>
 *         &lt;element name="units" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="missingValue" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="uncertainty" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="qcFlag" type="{http://ncei.noaa.gov/oads_metadata}qc_flag_info_type" minOccurs="0"/>
 *         &lt;element name="researcher" type="{http://ncei.noaa.gov/oads_metadata}person_reference_type"/>
 *         &lt;element name="methodReference" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "base_variable_type", propOrder = {
    "name",
    "description",
    "datasetVarName",
    "variableType",
    "observationType",
    "units",
    "missingValue",
    "uncertainty",
    "qcFlag",
    "researcher",
    "methodReference"
})
@XmlSeeAlso({
    DataVariable.class
})
public class BaseVariableType {

    @XmlElement(required = true)
    protected String name;
    @XmlElement(required = true)
    protected String description;
    @XmlElement(required = true)
    protected String datasetVarName;
    @XmlElement(required = true)
    protected String variableType;
    @XmlElement(required = true)
    protected String observationType;
    protected String units;
    protected String missingValue;
    protected String uncertainty;
    protected QcFlagInfoType qcFlag;
    @XmlElement(required = true)
    protected PersonReferenceType researcher;
    protected String methodReference;

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the datasetVarName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDatasetVarName() {
        return datasetVarName;
    }

    /**
     * Sets the value of the datasetVarName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDatasetVarName(String value) {
        this.datasetVarName = value;
    }

    /**
     * Gets the value of the variableType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVariableType() {
        return variableType;
    }

    /**
     * Sets the value of the variableType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVariableType(String value) {
        this.variableType = value;
    }

    /**
     * Gets the value of the observationType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getObservationType() {
        return observationType;
    }

    /**
     * Sets the value of the observationType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setObservationType(String value) {
        this.observationType = value;
    }

    /**
     * Gets the value of the units property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUnits() {
        return units;
    }

    /**
     * Sets the value of the units property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUnits(String value) {
        this.units = value;
    }

    /**
     * Gets the value of the missingValue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMissingValue() {
        return missingValue;
    }

    /**
     * Sets the value of the missingValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMissingValue(String value) {
        this.missingValue = value;
    }

    /**
     * Gets the value of the uncertainty property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUncertainty() {
        return uncertainty;
    }

    /**
     * Sets the value of the uncertainty property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUncertainty(String value) {
        this.uncertainty = value;
    }

    /**
     * Gets the value of the qcFlag property.
     * 
     * @return
     *     possible object is
     *     {@link QcFlagInfoType }
     *     
     */
    public QcFlagInfoType getQcFlag() {
        return qcFlag;
    }

    /**
     * Sets the value of the qcFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link QcFlagInfoType }
     *     
     */
    public void setQcFlag(QcFlagInfoType value) {
        this.qcFlag = value;
    }

    /**
     * Gets the value of the researcher property.
     * 
     * @return
     *     possible object is
     *     {@link PersonReferenceType }
     *     
     */
    public PersonReferenceType getResearcher() {
        return researcher;
    }

    /**
     * Sets the value of the researcher property.
     * 
     * @param value
     *     allowed object is
     *     {@link PersonReferenceType }
     *     
     */
    public void setResearcher(PersonReferenceType value) {
        this.researcher = value;
    }

    /**
     * Gets the value of the methodReference property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMethodReference() {
        return methodReference;
    }

    /**
     * Sets the value of the methodReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMethodReference(String value) {
        this.methodReference = value;
    }

}
