//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.03.06 at 08:47:27 AM PST 
//


package gov.noaa.pmel.oads.v_a0_2;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for co2_base complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="co2_base">
 *   &lt;complexContent>
 *     &lt;extension base="{http://ncei.noaa.gov/oads_metadata}measured_variable">
 *       &lt;sequence>
 *         &lt;element name="gasDetector" type="{http://ncei.noaa.gov/oads_metadata}gas_detector_type"/>
 *         &lt;element name="waterVaporCorrection" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="temperatureCorrection" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="co2ReportTemperature" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "co2_base", propOrder = {
    "gasDetector",
    "waterVaporCorrection",
    "temperatureCorrection",
    "co2ReportTemperature"
})
@XmlSeeAlso({
    Co2Atonomous.class,
    Co2Discrete.class
})
public class Co2Base
    extends MeasuredVariable
{

    @XmlElement(required = true)
    protected GasDetectorType gasDetector;
    @XmlElement(required = true)
    protected String waterVaporCorrection;
    @XmlElement(required = true)
    protected String temperatureCorrection;
    @XmlElement(required = true)
    protected String co2ReportTemperature;

    /**
     * Gets the value of the gasDetector property.
     * 
     * @return
     *     possible object is
     *     {@link GasDetectorType }
     *     
     */
    public GasDetectorType getGasDetector() {
        return gasDetector;
    }

    /**
     * Sets the value of the gasDetector property.
     * 
     * @param value
     *     allowed object is
     *     {@link GasDetectorType }
     *     
     */
    public void setGasDetector(GasDetectorType value) {
        this.gasDetector = value;
    }

    /**
     * Gets the value of the waterVaporCorrection property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWaterVaporCorrection() {
        return waterVaporCorrection;
    }

    /**
     * Sets the value of the waterVaporCorrection property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWaterVaporCorrection(String value) {
        this.waterVaporCorrection = value;
    }

    /**
     * Gets the value of the temperatureCorrection property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTemperatureCorrection() {
        return temperatureCorrection;
    }

    /**
     * Sets the value of the temperatureCorrection property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTemperatureCorrection(String value) {
        this.temperatureCorrection = value;
    }

    /**
     * Gets the value of the co2ReportTemperature property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCo2ReportTemperature() {
        return co2ReportTemperature;
    }

    /**
     * Sets the value of the co2ReportTemperature property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCo2ReportTemperature(String value) {
        this.co2ReportTemperature = value;
    }

}
