//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.03.06 at 08:47:27 AM PST 
//


package gov.noaa.pmel.oads.v_a0_2;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for co2_discrete complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="co2_discrete">
 *   &lt;complexContent>
 *     &lt;extension base="{http://ncei.noaa.gov/oads_metadata}co2_base">
 *       &lt;sequence>
 *         &lt;element name="storageMethod" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="seawaterVolume" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="headspaceVolume" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="measurementTemperature" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "co2_discrete", propOrder = {
    "storageMethod",
    "seawaterVolume",
    "headspaceVolume",
    "measurementTemperature"
})
public class Co2Discrete
    extends Co2Base
{

    @XmlElement(required = true)
    protected String storageMethod;
    @XmlElement(required = true)
    protected String seawaterVolume;
    @XmlElement(required = true)
    protected String headspaceVolume;
    @XmlElement(required = true)
    protected String measurementTemperature;

    /**
     * Gets the value of the storageMethod property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStorageMethod() {
        return storageMethod;
    }

    /**
     * Sets the value of the storageMethod property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStorageMethod(String value) {
        this.storageMethod = value;
    }

    /**
     * Gets the value of the seawaterVolume property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSeawaterVolume() {
        return seawaterVolume;
    }

    /**
     * Sets the value of the seawaterVolume property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSeawaterVolume(String value) {
        this.seawaterVolume = value;
    }

    /**
     * Gets the value of the headspaceVolume property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHeadspaceVolume() {
        return headspaceVolume;
    }

    /**
     * Sets the value of the headspaceVolume property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHeadspaceVolume(String value) {
        this.headspaceVolume = value;
    }

    /**
     * Gets the value of the measurementTemperature property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMeasurementTemperature() {
        return measurementTemperature;
    }

    /**
     * Sets the value of the measurementTemperature property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMeasurementTemperature(String value) {
        this.measurementTemperature = value;
    }

}
