//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.03.06 at 08:47:27 AM PST 
//


package gov.noaa.pmel.oads.v_a0_2;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for cruise_identifiers_collection complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="cruise_identifiers_collection">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice maxOccurs="unbounded">
 *         &lt;element name="expocode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="cruiseId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="identifier" type="{http://ncei.noaa.gov/oads_metadata}typed_identifier_type"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "cruise_identifiers_collection", propOrder = {
    "expocodeOrCruiseIdOrIdentifier"
})
public class CruiseIdentifiersCollection {

    @XmlElementRefs({
        @XmlElementRef(name = "expocode", namespace = "http://ncei.noaa.gov/oads_metadata", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "cruiseId", namespace = "http://ncei.noaa.gov/oads_metadata", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "identifier", namespace = "http://ncei.noaa.gov/oads_metadata", type = JAXBElement.class, required = false)
    })
    protected List<JAXBElement<?>> expocodeOrCruiseIdOrIdentifier;

    /**
     * Gets the value of the expocodeOrCruiseIdOrIdentifier property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the expocodeOrCruiseIdOrIdentifier property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getExpocodeOrCruiseIdOrIdentifier().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link TypedIdentifierType }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * 
     */
    public List<JAXBElement<?>> getExpocodeOrCruiseIdOrIdentifier() {
        if (expocodeOrCruiseIdOrIdentifier == null) {
            expocodeOrCruiseIdOrIdentifier = new ArrayList<JAXBElement<?>>();
        }
        return this.expocodeOrCruiseIdOrIdentifier;
    }

}
