//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.03.06 at 08:47:27 AM PST 
//


package gov.noaa.pmel.oads.v_a0_2;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for data_variable complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="data_variable">
 *   &lt;complexContent>
 *     &lt;extension base="{http://ncei.noaa.gov/oads_metadata}base_variable_type">
 *       &lt;sequence>
 *         &lt;element name="manipulationMethod" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "data_variable", propOrder = {
    "manipulationMethod"
})
@XmlSeeAlso({
    MeasuredVariable.class,
    ComputedVariable.class
})
public class DataVariable
    extends BaseVariableType
{

    protected String manipulationMethod;

    /**
     * Gets the value of the manipulationMethod property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getManipulationMethod() {
        return manipulationMethod;
    }

    /**
     * Sets the value of the manipulationMethod property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setManipulationMethod(String value) {
        this.manipulationMethod = value;
    }

}
