//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.03.06 at 08:47:27 AM PST 
//


package gov.noaa.pmel.oads.v_a0_2;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for dic_sample_type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="dic_sample_type">
 *   &lt;complexContent>
 *     &lt;extension base="{http://ncei.noaa.gov/oads_metadata}measured_variable">
 *       &lt;sequence>
 *         &lt;element name="poison" type="{http://ncei.noaa.gov/oads_metadata}poison_type" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "dic_sample_type", propOrder = {
    "poison"
})
@XmlSeeAlso({
    TaSampleType.class
})
public class DicSampleType
    extends MeasuredVariable
{

    protected PoisonType poison;

    /**
     * Gets the value of the poison property.
     * 
     * @return
     *     possible object is
     *     {@link PoisonType }
     *     
     */
    public PoisonType getPoison() {
        return poison;
    }

    /**
     * Sets the value of the poison property.
     * 
     * @param value
     *     allowed object is
     *     {@link PoisonType }
     *     
     */
    public void setPoison(PoisonType value) {
        this.poison = value;
    }

}
