//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.03.06 at 08:47:27 AM PST 
//


package gov.noaa.pmel.oads.v_a0_2;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for geospatial_extents_type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="geospatial_extents_type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="westernBounds" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="easternBounds" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="northernBounds" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="southernBounds" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "geospatial_extents_type", propOrder = {
    "westernBounds",
    "easternBounds",
    "northernBounds",
    "southernBounds"
})
public class GeospatialExtentsType {

    @XmlElement(required = true)
    protected BigDecimal westernBounds;
    @XmlElement(required = true)
    protected BigDecimal easternBounds;
    @XmlElement(required = true)
    protected BigDecimal northernBounds;
    @XmlElement(required = true)
    protected BigDecimal southernBounds;

    /**
     * Gets the value of the westernBounds property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getWesternBounds() {
        return westernBounds;
    }

    /**
     * Sets the value of the westernBounds property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setWesternBounds(BigDecimal value) {
        this.westernBounds = value;
    }

    /**
     * Gets the value of the easternBounds property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getEasternBounds() {
        return easternBounds;
    }

    /**
     * Sets the value of the easternBounds property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setEasternBounds(BigDecimal value) {
        this.easternBounds = value;
    }

    /**
     * Gets the value of the northernBounds property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getNorthernBounds() {
        return northernBounds;
    }

    /**
     * Sets the value of the northernBounds property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setNorthernBounds(BigDecimal value) {
        this.northernBounds = value;
    }

    /**
     * Gets the value of the southernBounds property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getSouthernBounds() {
        return southernBounds;
    }

    /**
     * Sets the value of the southernBounds property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setSouthernBounds(BigDecimal value) {
        this.southernBounds = value;
    }

}
