//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.03.06 at 08:47:27 AM PST 
//


package gov.noaa.pmel.oads.v_a0_2;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for measured_variable complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="measured_variable">
 *   &lt;complexContent>
 *     &lt;extension base="{http://ncei.noaa.gov/oads_metadata}data_variable">
 *       &lt;sequence>
 *         &lt;element name="samplingInstrument" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="analyzingInstrument" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="detailedInfo" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="fieldReplicateHandling" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="standardization" type="{http://ncei.noaa.gov/oads_metadata}standardization_type" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "measured_variable", propOrder = {
    "samplingInstrument",
    "analyzingInstrument",
    "detailedInfo",
    "fieldReplicateHandling",
    "standardization"
})
@XmlSeeAlso({
    Co2Base.class,
    PhSampleType.class,
    DicSampleType.class
})
public class MeasuredVariable
    extends DataVariable
{

    protected String samplingInstrument;
    protected String analyzingInstrument;
    protected String detailedInfo;
    protected String fieldReplicateHandling;
    protected StandardizationType standardization;

    /**
     * Gets the value of the samplingInstrument property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSamplingInstrument() {
        return samplingInstrument;
    }

    /**
     * Sets the value of the samplingInstrument property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSamplingInstrument(String value) {
        this.samplingInstrument = value;
    }

    /**
     * Gets the value of the analyzingInstrument property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAnalyzingInstrument() {
        return analyzingInstrument;
    }

    /**
     * Sets the value of the analyzingInstrument property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAnalyzingInstrument(String value) {
        this.analyzingInstrument = value;
    }

    /**
     * Gets the value of the detailedInfo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDetailedInfo() {
        return detailedInfo;
    }

    /**
     * Sets the value of the detailedInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDetailedInfo(String value) {
        this.detailedInfo = value;
    }

    /**
     * Gets the value of the fieldReplicateHandling property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFieldReplicateHandling() {
        return fieldReplicateHandling;
    }

    /**
     * Sets the value of the fieldReplicateHandling property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFieldReplicateHandling(String value) {
        this.fieldReplicateHandling = value;
    }

    /**
     * Gets the value of the standardization property.
     * 
     * @return
     *     possible object is
     *     {@link StandardizationType }
     *     
     */
    public StandardizationType getStandardization() {
        return standardization;
    }

    /**
     * Sets the value of the standardization property.
     * 
     * @param value
     *     allowed object is
     *     {@link StandardizationType }
     *     
     */
    public void setStandardization(StandardizationType value) {
        this.standardization = value;
    }

}
