//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.03.06 at 08:47:27 AM PST 
//


package gov.noaa.pmel.oads.v_a0_2;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for oads_metadata_document_type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="oads_metadata_document_type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="investigators" type="{http://ncei.noaa.gov/oads_metadata}investigators_collection"/>
 *         &lt;element name="dataSubmitter" type="{http://ncei.noaa.gov/oads_metadata}person_type"/>
 *         &lt;element name="title" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="abstract" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="purpose" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="temporalExtents" type="{http://ncei.noaa.gov/oads_metadata}temporal_extents_type"/>
 *         &lt;element name="geospatialExtents" type="{http://ncei.noaa.gov/oads_metadata}geospatial_extents_type"/>
 *         &lt;element name="geospatialReference" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="sampleCollectionRegions" type="{http://ncei.noaa.gov/oads_metadata}geographic_region_name_collection"/>
 *         &lt;element name="organismCollectionRegions" type="{http://ncei.noaa.gov/oads_metadata}geographic_region_name_collection" minOccurs="0"/>
 *         &lt;element name="fundingInformation" type="{http://ncei.noaa.gov/oads_metadata}funding_information_type"/>
 *         &lt;element name="researchProjects" type="{http://ncei.noaa.gov/oads_metadata}research_project_collection" minOccurs="0"/>
 *         &lt;element name="platforms" type="{http://ncei.noaa.gov/oads_metadata}platform_collection"/>
 *         &lt;element name="cruiseIdentifiers" type="{http://ncei.noaa.gov/oads_metadata}cruise_identifiers_collection"/>
 *         &lt;element name="section" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="citation" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="references" type="{http://ncei.noaa.gov/oads_metadata}general_string_collection" minOccurs="0"/>
 *         &lt;element name="keywords" type="{http://ncei.noaa.gov/oads_metadata}general_string_collection" minOccurs="0"/>
 *         &lt;element name="supplementalInformation" type="{http://ncei.noaa.gov/oads_metadata}mixed_collection" minOccurs="0"/>
 *         &lt;element name="variables" type="{http://ncei.noaa.gov/oads_metadata}variable_collection"/>
 *         &lt;element name="update" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *       &lt;attribute name="version" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "oads_metadata_document_type", propOrder = {
    "investigators",
    "dataSubmitter",
    "title",
    "_abstract",
    "purpose",
    "temporalExtents",
    "geospatialExtents",
    "geospatialReference",
    "sampleCollectionRegions",
    "organismCollectionRegions",
    "fundingInformation",
    "researchProjects",
    "platforms",
    "cruiseIdentifiers",
    "section",
    "citation",
    "references",
    "keywords",
    "supplementalInformation",
    "variables",
    "update"
})
public class OadsMetadataDocumentType {

    @XmlElement(required = true)
    protected InvestigatorsCollection investigators;
    @XmlElement(required = true)
    protected PersonType dataSubmitter;
    @XmlElement(required = true)
    protected String title;
    @XmlElement(name = "abstract", required = true)
    protected String _abstract;
    @XmlElement(required = true)
    protected String purpose;
    @XmlElement(required = true)
    protected TemporalExtentsType temporalExtents;
    @XmlElement(required = true)
    protected GeospatialExtentsType geospatialExtents;
    @XmlElement(required = true)
    protected String geospatialReference;
    @XmlElement(required = true)
    protected GeographicRegionNameCollection sampleCollectionRegions;
    protected GeographicRegionNameCollection organismCollectionRegions;
    @XmlElement(required = true)
    protected FundingInformationType fundingInformation;
    protected ResearchProjectCollection researchProjects;
    @XmlElement(required = true)
    protected PlatformCollection platforms;
    @XmlElement(required = true)
    protected CruiseIdentifiersCollection cruiseIdentifiers;
    protected String section;
    protected String citation;
    protected GeneralStringCollection references;
    protected GeneralStringCollection keywords;
    protected MixedCollection supplementalInformation;
    @XmlElement(required = true)
    protected VariableCollection variables;
    @XmlElement(required = true)
    protected String update;
    @XmlAttribute(name = "version", required = true)
    protected String version;

    /**
     * Gets the value of the investigators property.
     * 
     * @return
     *     possible object is
     *     {@link InvestigatorsCollection }
     *     
     */
    public InvestigatorsCollection getInvestigators() {
        return investigators;
    }

    /**
     * Sets the value of the investigators property.
     * 
     * @param value
     *     allowed object is
     *     {@link InvestigatorsCollection }
     *     
     */
    public void setInvestigators(InvestigatorsCollection value) {
        this.investigators = value;
    }

    /**
     * Gets the value of the dataSubmitter property.
     * 
     * @return
     *     possible object is
     *     {@link PersonType }
     *     
     */
    public PersonType getDataSubmitter() {
        return dataSubmitter;
    }

    /**
     * Sets the value of the dataSubmitter property.
     * 
     * @param value
     *     allowed object is
     *     {@link PersonType }
     *     
     */
    public void setDataSubmitter(PersonType value) {
        this.dataSubmitter = value;
    }

    /**
     * Gets the value of the title property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTitle() {
        return title;
    }

    /**
     * Sets the value of the title property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTitle(String value) {
        this.title = value;
    }

    /**
     * Gets the value of the abstract property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAbstract() {
        return _abstract;
    }

    /**
     * Sets the value of the abstract property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAbstract(String value) {
        this._abstract = value;
    }

    /**
     * Gets the value of the purpose property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPurpose() {
        return purpose;
    }

    /**
     * Sets the value of the purpose property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPurpose(String value) {
        this.purpose = value;
    }

    /**
     * Gets the value of the temporalExtents property.
     * 
     * @return
     *     possible object is
     *     {@link TemporalExtentsType }
     *     
     */
    public TemporalExtentsType getTemporalExtents() {
        return temporalExtents;
    }

    /**
     * Sets the value of the temporalExtents property.
     * 
     * @param value
     *     allowed object is
     *     {@link TemporalExtentsType }
     *     
     */
    public void setTemporalExtents(TemporalExtentsType value) {
        this.temporalExtents = value;
    }

    /**
     * Gets the value of the geospatialExtents property.
     * 
     * @return
     *     possible object is
     *     {@link GeospatialExtentsType }
     *     
     */
    public GeospatialExtentsType getGeospatialExtents() {
        return geospatialExtents;
    }

    /**
     * Sets the value of the geospatialExtents property.
     * 
     * @param value
     *     allowed object is
     *     {@link GeospatialExtentsType }
     *     
     */
    public void setGeospatialExtents(GeospatialExtentsType value) {
        this.geospatialExtents = value;
    }

    /**
     * Gets the value of the geospatialReference property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGeospatialReference() {
        return geospatialReference;
    }

    /**
     * Sets the value of the geospatialReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGeospatialReference(String value) {
        this.geospatialReference = value;
    }

    /**
     * Gets the value of the sampleCollectionRegions property.
     * 
     * @return
     *     possible object is
     *     {@link GeographicRegionNameCollection }
     *     
     */
    public GeographicRegionNameCollection getSampleCollectionRegions() {
        return sampleCollectionRegions;
    }

    /**
     * Sets the value of the sampleCollectionRegions property.
     * 
     * @param value
     *     allowed object is
     *     {@link GeographicRegionNameCollection }
     *     
     */
    public void setSampleCollectionRegions(GeographicRegionNameCollection value) {
        this.sampleCollectionRegions = value;
    }

    /**
     * Gets the value of the organismCollectionRegions property.
     * 
     * @return
     *     possible object is
     *     {@link GeographicRegionNameCollection }
     *     
     */
    public GeographicRegionNameCollection getOrganismCollectionRegions() {
        return organismCollectionRegions;
    }

    /**
     * Sets the value of the organismCollectionRegions property.
     * 
     * @param value
     *     allowed object is
     *     {@link GeographicRegionNameCollection }
     *     
     */
    public void setOrganismCollectionRegions(GeographicRegionNameCollection value) {
        this.organismCollectionRegions = value;
    }

    /**
     * Gets the value of the fundingInformation property.
     * 
     * @return
     *     possible object is
     *     {@link FundingInformationType }
     *     
     */
    public FundingInformationType getFundingInformation() {
        return fundingInformation;
    }

    /**
     * Sets the value of the fundingInformation property.
     * 
     * @param value
     *     allowed object is
     *     {@link FundingInformationType }
     *     
     */
    public void setFundingInformation(FundingInformationType value) {
        this.fundingInformation = value;
    }

    /**
     * Gets the value of the researchProjects property.
     * 
     * @return
     *     possible object is
     *     {@link ResearchProjectCollection }
     *     
     */
    public ResearchProjectCollection getResearchProjects() {
        return researchProjects;
    }

    /**
     * Sets the value of the researchProjects property.
     * 
     * @param value
     *     allowed object is
     *     {@link ResearchProjectCollection }
     *     
     */
    public void setResearchProjects(ResearchProjectCollection value) {
        this.researchProjects = value;
    }

    /**
     * Gets the value of the platforms property.
     * 
     * @return
     *     possible object is
     *     {@link PlatformCollection }
     *     
     */
    public PlatformCollection getPlatforms() {
        return platforms;
    }

    /**
     * Sets the value of the platforms property.
     * 
     * @param value
     *     allowed object is
     *     {@link PlatformCollection }
     *     
     */
    public void setPlatforms(PlatformCollection value) {
        this.platforms = value;
    }

    /**
     * Gets the value of the cruiseIdentifiers property.
     * 
     * @return
     *     possible object is
     *     {@link CruiseIdentifiersCollection }
     *     
     */
    public CruiseIdentifiersCollection getCruiseIdentifiers() {
        return cruiseIdentifiers;
    }

    /**
     * Sets the value of the cruiseIdentifiers property.
     * 
     * @param value
     *     allowed object is
     *     {@link CruiseIdentifiersCollection }
     *     
     */
    public void setCruiseIdentifiers(CruiseIdentifiersCollection value) {
        this.cruiseIdentifiers = value;
    }

    /**
     * Gets the value of the section property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSection() {
        return section;
    }

    /**
     * Sets the value of the section property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSection(String value) {
        this.section = value;
    }

    /**
     * Gets the value of the citation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCitation() {
        return citation;
    }

    /**
     * Sets the value of the citation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCitation(String value) {
        this.citation = value;
    }

    /**
     * Gets the value of the references property.
     * 
     * @return
     *     possible object is
     *     {@link GeneralStringCollection }
     *     
     */
    public GeneralStringCollection getReferences() {
        return references;
    }

    /**
     * Sets the value of the references property.
     * 
     * @param value
     *     allowed object is
     *     {@link GeneralStringCollection }
     *     
     */
    public void setReferences(GeneralStringCollection value) {
        this.references = value;
    }

    /**
     * Gets the value of the keywords property.
     * 
     * @return
     *     possible object is
     *     {@link GeneralStringCollection }
     *     
     */
    public GeneralStringCollection getKeywords() {
        return keywords;
    }

    /**
     * Sets the value of the keywords property.
     * 
     * @param value
     *     allowed object is
     *     {@link GeneralStringCollection }
     *     
     */
    public void setKeywords(GeneralStringCollection value) {
        this.keywords = value;
    }

    /**
     * Gets the value of the supplementalInformation property.
     * 
     * @return
     *     possible object is
     *     {@link MixedCollection }
     *     
     */
    public MixedCollection getSupplementalInformation() {
        return supplementalInformation;
    }

    /**
     * Sets the value of the supplementalInformation property.
     * 
     * @param value
     *     allowed object is
     *     {@link MixedCollection }
     *     
     */
    public void setSupplementalInformation(MixedCollection value) {
        this.supplementalInformation = value;
    }

    /**
     * Gets the value of the variables property.
     * 
     * @return
     *     possible object is
     *     {@link VariableCollection }
     *     
     */
    public VariableCollection getVariables() {
        return variables;
    }

    /**
     * Sets the value of the variables property.
     * 
     * @param value
     *     allowed object is
     *     {@link VariableCollection }
     *     
     */
    public void setVariables(VariableCollection value) {
        this.variables = value;
    }

    /**
     * Gets the value of the update property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUpdate() {
        return update;
    }

    /**
     * Sets the value of the update property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUpdate(String value) {
        this.update = value;
    }

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVersion() {
        return version;
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVersion(String value) {
        this.version = value;
    }

}
