//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.03.06 at 08:47:27 AM PST 
//


package gov.noaa.pmel.oads.v_a0_2;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the gov.noaa.pmel.oads.v_a0_2 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _CruiseId_QNAME = new QName("http://ncei.noaa.gov/oads_metadata", "cruiseId");
    private final static QName _Keyword_QNAME = new QName("http://ncei.noaa.gov/oads_metadata", "keyword");
    private final static QName _AbstractString_QNAME = new QName("http://ncei.noaa.gov/oads_metadata", "abstract_string");
    private final static QName _Id_QNAME = new QName("http://ncei.noaa.gov/oads_metadata", "id");
    private final static QName _OadsMetadata_QNAME = new QName("http://ncei.noaa.gov/oads_metadata", "oads_metadata");
    private final static QName _Author_QNAME = new QName("http://ncei.noaa.gov/oads_metadata", "author");
    private final static QName _Code_QNAME = new QName("http://ncei.noaa.gov/oads_metadata", "code");
    private final static QName _Expocode_QNAME = new QName("http://ncei.noaa.gov/oads_metadata", "expocode");
    private final static QName _Reference_QNAME = new QName("http://ncei.noaa.gov/oads_metadata", "reference");
    private final static QName _CruiseIdentifiersCollectionIdentifier_QNAME = new QName("http://ncei.noaa.gov/oads_metadata", "identifier");
    private final static QName _PersonContactInfoTypeEmail_QNAME = new QName("http://ncei.noaa.gov/oads_metadata", "email");
    private final static QName _PersonContactInfoTypeLink_QNAME = new QName("http://ncei.noaa.gov/oads_metadata", "link");
    private final static QName _PersonContactInfoTypePhone_QNAME = new QName("http://ncei.noaa.gov/oads_metadata", "phone");
    private final static QName _PersonContactInfoTypeAddress_QNAME = new QName("http://ncei.noaa.gov/oads_metadata", "address");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: gov.noaa.pmel.oads.v_a0_2
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link EquilibratorSensorType }
     * 
     */
    public EquilibratorSensorType createEquilibratorSensorType() {
        return new EquilibratorSensorType();
    }

    /**
     * Create an instance of {@link StandardizationType }
     * 
     */
    public StandardizationType createStandardizationType() {
        return new StandardizationType();
    }

    /**
     * Create an instance of {@link CalculationMethodType }
     * 
     */
    public CalculationMethodType createCalculationMethodType() {
        return new CalculationMethodType();
    }

    /**
     * Create an instance of {@link OadsMetadataDocumentType }
     * 
     */
    public OadsMetadataDocumentType createOadsMetadataDocumentType() {
        return new OadsMetadataDocumentType();
    }

    /**
     * Create an instance of {@link PersonContactInfoType }
     * 
     */
    public PersonContactInfoType createPersonContactInfoType() {
        return new PersonContactInfoType();
    }

    /**
     * Create an instance of {@link TypedIdentifierType }
     * 
     */
    public TypedIdentifierType createTypedIdentifierType() {
        return new TypedIdentifierType();
    }

    /**
     * Create an instance of {@link GasDetectorType }
     * 
     */
    public GasDetectorType createGasDetectorType() {
        return new GasDetectorType();
    }

    /**
     * Create an instance of {@link VariableCollection }
     * 
     */
    public VariableCollection createVariableCollection() {
        return new VariableCollection();
    }

    /**
     * Create an instance of {@link Co2Atonomous }
     * 
     */
    public Co2Atonomous createCo2Atonomous() {
        return new Co2Atonomous();
    }

    /**
     * Create an instance of {@link InvestigatorsCollection }
     * 
     */
    public InvestigatorsCollection createInvestigatorsCollection() {
        return new InvestigatorsCollection();
    }

    /**
     * Create an instance of {@link DicSampleType }
     * 
     */
    public DicSampleType createDicSampleType() {
        return new DicSampleType();
    }

    /**
     * Create an instance of {@link Co2Base }
     * 
     */
    public Co2Base createCo2Base() {
        return new Co2Base();
    }

    /**
     * Create an instance of {@link PoisonType }
     * 
     */
    public PoisonType createPoisonType() {
        return new PoisonType();
    }

    /**
     * Create an instance of {@link TypedElementType }
     * 
     */
    public TypedElementType createTypedElementType() {
        return new TypedElementType();
    }

    /**
     * Create an instance of {@link PlatformType }
     * 
     */
    public PlatformType createPlatformType() {
        return new PlatformType();
    }

    /**
     * Create an instance of {@link CruiseIdentifiersCollection }
     * 
     */
    public CruiseIdentifiersCollection createCruiseIdentifiersCollection() {
        return new CruiseIdentifiersCollection();
    }

    /**
     * Create an instance of {@link QcFlagInfoType }
     * 
     */
    public QcFlagInfoType createQcFlagInfoType() {
        return new QcFlagInfoType();
    }

    /**
     * Create an instance of {@link EquilibratorType }
     * 
     */
    public EquilibratorType createEquilibratorType() {
        return new EquilibratorType();
    }

    /**
     * Create an instance of {@link AltitudeRangeType }
     * 
     */
    public AltitudeRangeType createAltitudeRangeType() {
        return new AltitudeRangeType();
    }

    /**
     * Create an instance of {@link PersonNameType }
     * 
     */
    public PersonNameType createPersonNameType() {
        return new PersonNameType();
    }

    /**
     * Create an instance of {@link OrderedStringElementType }
     * 
     */
    public OrderedStringElementType createOrderedStringElementType() {
        return new OrderedStringElementType();
    }

    /**
     * Create an instance of {@link MeasuredVariable }
     * 
     */
    public MeasuredVariable createMeasuredVariable() {
        return new MeasuredVariable();
    }

    /**
     * Create an instance of {@link ArchiveInfoType }
     * 
     */
    public ArchiveInfoType createArchiveInfoType() {
        return new ArchiveInfoType();
    }

    /**
     * Create an instance of {@link PersonCollection }
     * 
     */
    public PersonCollection createPersonCollection() {
        return new PersonCollection();
    }

    /**
     * Create an instance of {@link DataVariable }
     * 
     */
    public DataVariable createDataVariable() {
        return new DataVariable();
    }

    /**
     * Create an instance of {@link FundingInformationType }
     * 
     */
    public FundingInformationType createFundingInformationType() {
        return new FundingInformationType();
    }

    /**
     * Create an instance of {@link TypedStringType }
     * 
     */
    public TypedStringType createTypedStringType() {
        return new TypedStringType();
    }

    /**
     * Create an instance of {@link Co2Discrete }
     * 
     */
    public Co2Discrete createCo2Discrete() {
        return new Co2Discrete();
    }

    /**
     * Create an instance of {@link ResearchProjectType }
     * 
     */
    public ResearchProjectType createResearchProjectType() {
        return new ResearchProjectType();
    }

    /**
     * Create an instance of {@link DepthRangeType }
     * 
     */
    public DepthRangeType createDepthRangeType() {
        return new DepthRangeType();
    }

    /**
     * Create an instance of {@link PhSampleType }
     * 
     */
    public PhSampleType createPhSampleType() {
        return new PhSampleType();
    }

    /**
     * Create an instance of {@link PersonType }
     * 
     */
    public PersonType createPersonType() {
        return new PersonType();
    }

    /**
     * Create an instance of {@link ResearchProjectCollection }
     * 
     */
    public ResearchProjectCollection createResearchProjectCollection() {
        return new ResearchProjectCollection();
    }

    /**
     * Create an instance of {@link ValueWithUnitType }
     * 
     */
    public ValueWithUnitType createValueWithUnitType() {
        return new ValueWithUnitType();
    }

    /**
     * Create an instance of {@link PlatformCollection }
     * 
     */
    public PlatformCollection createPlatformCollection() {
        return new PlatformCollection();
    }

    /**
     * Create an instance of {@link MixedCollection }
     * 
     */
    public MixedCollection createMixedCollection() {
        return new MixedCollection();
    }

    /**
     * Create an instance of {@link GeospatialExtentsType }
     * 
     */
    public GeospatialExtentsType createGeospatialExtentsType() {
        return new GeospatialExtentsType();
    }

    /**
     * Create an instance of {@link AddressType }
     * 
     */
    public AddressType createAddressType() {
        return new AddressType();
    }

    /**
     * Create an instance of {@link BiologicalVariable }
     * 
     */
    public BiologicalVariable createBiologicalVariable() {
        return new BiologicalVariable();
    }

    /**
     * Create an instance of {@link TemporalExtentsType }
     * 
     */
    public TemporalExtentsType createTemporalExtentsType() {
        return new TemporalExtentsType();
    }

    /**
     * Create an instance of {@link GeographicRegionNameCollection }
     * 
     */
    public GeographicRegionNameCollection createGeographicRegionNameCollection() {
        return new GeographicRegionNameCollection();
    }

    /**
     * Create an instance of {@link TaSampleType }
     * 
     */
    public TaSampleType createTaSampleType() {
        return new TaSampleType();
    }

    /**
     * Create an instance of {@link ComputedVariable }
     * 
     */
    public ComputedVariable createComputedVariable() {
        return new ComputedVariable();
    }

    /**
     * Create an instance of {@link GeneralStringCollection }
     * 
     */
    public GeneralStringCollection createGeneralStringCollection() {
        return new GeneralStringCollection();
    }

    /**
     * Create an instance of {@link PersonReferenceType }
     * 
     */
    public PersonReferenceType createPersonReferenceType() {
        return new PersonReferenceType();
    }

    /**
     * Create an instance of {@link CrmType }
     * 
     */
    public CrmType createCrmType() {
        return new CrmType();
    }

    /**
     * Create an instance of {@link FundingSourceType }
     * 
     */
    public FundingSourceType createFundingSourceType() {
        return new FundingSourceType();
    }

    /**
     * Create an instance of {@link BaseVariableType }
     * 
     */
    public BaseVariableType createBaseVariableType() {
        return new BaseVariableType();
    }

    /**
     * Create an instance of {@link EquilibratorSensorType.Sensor }
     * 
     */
    public EquilibratorSensorType.Sensor createEquilibratorSensorTypeSensor() {
        return new EquilibratorSensorType.Sensor();
    }

    /**
     * Create an instance of {@link StandardizationType.StandardGas }
     * 
     */
    public StandardizationType.StandardGas createStandardizationTypeStandardGas() {
        return new StandardizationType.StandardGas();
    }

    /**
     * Create an instance of {@link CalculationMethodType.Parameter }
     * 
     */
    public CalculationMethodType.Parameter createCalculationMethodTypeParameter() {
        return new CalculationMethodType.Parameter();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ncei.noaa.gov/oads_metadata", name = "cruiseId", substitutionHeadNamespace = "http://ncei.noaa.gov/oads_metadata", substitutionHeadName = "abstract_string")
    public JAXBElement<String> createCruiseId(String value) {
        return new JAXBElement<String>(_CruiseId_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ncei.noaa.gov/oads_metadata", name = "keyword", substitutionHeadNamespace = "http://ncei.noaa.gov/oads_metadata", substitutionHeadName = "abstract_string")
    public JAXBElement<String> createKeyword(String value) {
        return new JAXBElement<String>(_Keyword_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ncei.noaa.gov/oads_metadata", name = "abstract_string")
    public JAXBElement<String> createAbstractString(String value) {
        return new JAXBElement<String>(_AbstractString_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ncei.noaa.gov/oads_metadata", name = "id", substitutionHeadNamespace = "http://ncei.noaa.gov/oads_metadata", substitutionHeadName = "abstract_string")
    public JAXBElement<String> createId(String value) {
        return new JAXBElement<String>(_Id_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OadsMetadataDocumentType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ncei.noaa.gov/oads_metadata", name = "oads_metadata")
    public JAXBElement<OadsMetadataDocumentType> createOadsMetadata(OadsMetadataDocumentType value) {
        return new JAXBElement<OadsMetadataDocumentType>(_OadsMetadata_QNAME, OadsMetadataDocumentType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ncei.noaa.gov/oads_metadata", name = "author", substitutionHeadNamespace = "http://ncei.noaa.gov/oads_metadata", substitutionHeadName = "abstract_string")
    public JAXBElement<String> createAuthor(String value) {
        return new JAXBElement<String>(_Author_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ncei.noaa.gov/oads_metadata", name = "code", substitutionHeadNamespace = "http://ncei.noaa.gov/oads_metadata", substitutionHeadName = "abstract_string")
    public JAXBElement<String> createCode(String value) {
        return new JAXBElement<String>(_Code_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ncei.noaa.gov/oads_metadata", name = "expocode", substitutionHeadNamespace = "http://ncei.noaa.gov/oads_metadata", substitutionHeadName = "abstract_string")
    public JAXBElement<String> createExpocode(String value) {
        return new JAXBElement<String>(_Expocode_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ncei.noaa.gov/oads_metadata", name = "reference", substitutionHeadNamespace = "http://ncei.noaa.gov/oads_metadata", substitutionHeadName = "abstract_string")
    public JAXBElement<String> createReference(String value) {
        return new JAXBElement<String>(_Reference_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ncei.noaa.gov/oads_metadata", name = "cruiseId", scope = CruiseIdentifiersCollection.class)
    public JAXBElement<String> createCruiseIdentifiersCollectionCruiseId(String value) {
        return new JAXBElement<String>(_CruiseId_QNAME, String.class, CruiseIdentifiersCollection.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ncei.noaa.gov/oads_metadata", name = "expocode", scope = CruiseIdentifiersCollection.class)
    public JAXBElement<String> createCruiseIdentifiersCollectionExpocode(String value) {
        return new JAXBElement<String>(_Expocode_QNAME, String.class, CruiseIdentifiersCollection.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TypedIdentifierType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ncei.noaa.gov/oads_metadata", name = "identifier", scope = CruiseIdentifiersCollection.class)
    public JAXBElement<TypedIdentifierType> createCruiseIdentifiersCollectionIdentifier(TypedIdentifierType value) {
        return new JAXBElement<TypedIdentifierType>(_CruiseIdentifiersCollectionIdentifier_QNAME, TypedIdentifierType.class, CruiseIdentifiersCollection.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TypedStringType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ncei.noaa.gov/oads_metadata", name = "email", scope = PersonContactInfoType.class)
    public JAXBElement<TypedStringType> createPersonContactInfoTypeEmail(TypedStringType value) {
        return new JAXBElement<TypedStringType>(_PersonContactInfoTypeEmail_QNAME, TypedStringType.class, PersonContactInfoType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ncei.noaa.gov/oads_metadata", name = "link", scope = PersonContactInfoType.class)
    public JAXBElement<String> createPersonContactInfoTypeLink(String value) {
        return new JAXBElement<String>(_PersonContactInfoTypeLink_QNAME, String.class, PersonContactInfoType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TypedStringType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ncei.noaa.gov/oads_metadata", name = "phone", scope = PersonContactInfoType.class)
    public JAXBElement<TypedStringType> createPersonContactInfoTypePhone(TypedStringType value) {
        return new JAXBElement<TypedStringType>(_PersonContactInfoTypePhone_QNAME, TypedStringType.class, PersonContactInfoType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AddressType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ncei.noaa.gov/oads_metadata", name = "address", scope = PersonContactInfoType.class)
    public JAXBElement<AddressType> createPersonContactInfoTypeAddress(AddressType value) {
        return new JAXBElement<AddressType>(_PersonContactInfoTypeAddress_QNAME, AddressType.class, PersonContactInfoType.class, value);
    }

}
