//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.03.06 at 08:47:27 AM PST 
//


package gov.noaa.pmel.oads.v_a0_2;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for person_contact_info_type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="person_contact_info_type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice maxOccurs="unbounded">
 *         &lt;element name="address" type="{http://ncei.noaa.gov/oads_metadata}address_type"/>
 *         &lt;element name="phone" type="{http://ncei.noaa.gov/oads_metadata}typed_string_type"/>
 *         &lt;element name="email" type="{http://ncei.noaa.gov/oads_metadata}typed_string_type"/>
 *         &lt;element name="link" type="{http://www.w3.org/2001/XMLSchema}anyURI" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "person_contact_info_type", propOrder = {
    "addressOrPhoneOrEmail"
})
public class PersonContactInfoType {

    @XmlElementRefs({
        @XmlElementRef(name = "link", namespace = "http://ncei.noaa.gov/oads_metadata", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "phone", namespace = "http://ncei.noaa.gov/oads_metadata", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "email", namespace = "http://ncei.noaa.gov/oads_metadata", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "address", namespace = "http://ncei.noaa.gov/oads_metadata", type = JAXBElement.class, required = false)
    })
    protected List<JAXBElement<?>> addressOrPhoneOrEmail;

    /**
     * Gets the value of the addressOrPhoneOrEmail property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the addressOrPhoneOrEmail property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAddressOrPhoneOrEmail().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JAXBElement }{@code <}{@link AddressType }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link TypedStringType }{@code >}
     * {@link JAXBElement }{@code <}{@link TypedStringType }{@code >}
     * 
     * 
     */
    public List<JAXBElement<?>> getAddressOrPhoneOrEmail() {
        if (addressOrPhoneOrEmail == null) {
            addressOrPhoneOrEmail = new ArrayList<JAXBElement<?>>();
        }
        return this.addressOrPhoneOrEmail;
    }

}
