//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.03.06 at 08:47:27 AM PST 
//


package gov.noaa.pmel.oads.v_a0_2;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for xx_observation_type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="xx_observation_type">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="Point"/>
 *     &lt;enumeration value="Timeseries"/>
 *     &lt;enumeration value="Trajectory"/>
 *     &lt;enumeration value="Profile"/>
 *     &lt;enumeration value="Timeseries_Profile"/>
 *     &lt;enumeration value="Trajectory_Profile"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "xx_observation_type")
@XmlEnum
public enum XxObservationType {

    @XmlEnumValue("Point")
    POINT("Point"),
    @XmlEnumValue("Timeseries")
    TIMESERIES("Timeseries"),
    @XmlEnumValue("Trajectory")
    TRAJECTORY("Trajectory"),
    @XmlEnumValue("Profile")
    PROFILE("Profile"),
    @XmlEnumValue("Timeseries_Profile")
    TIMESERIES_PROFILE("Timeseries_Profile"),
    @XmlEnumValue("Trajectory_Profile")
    TRAJECTORY_PROFILE("Trajectory_Profile");
    private final String value;

    XxObservationType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static XxObservationType fromValue(String v) {
        for (XxObservationType c: XxObservationType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
