//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.03.06 at 08:47:27 AM PST 
//


package gov.noaa.pmel.oads.v_a0_2;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for xx_variable_type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="xx_variable_type">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="UNSPECIFIED"/>
 *     &lt;enumeration value="IN_SITU"/>
 *     &lt;enumeration value="DISCRETE"/>
 *     &lt;enumeration value="COMPUTED"/>
 *     &lt;enumeration value="EXPERIMENT"/>
 *     &lt;enumeration value="MANIPULATION"/>
 *     &lt;enumeration value="RESPONSE"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "xx_variable_type")
@XmlEnum
public enum XxVariableType {

    UNSPECIFIED,
    IN_SITU,
    DISCRETE,
    COMPUTED,
    EXPERIMENT,
    MANIPULATION,
    RESPONSE;

    public String value() {
        return name();
    }

    public static XxVariableType fromValue(String v) {
        return valueOf(v);
    }

}
