//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.03.29 at 04:20:46 PM PDT 
//


package gov.noaa.ncei.oads.xml.v_a0_2_2;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;
import lombok.AllArgsConstructor;
import lombok.NoArgsConstructor;
import lombok.ToString;
import lombok.experimental.SuperBuilder;


/**
 * <p>Java class for base_variable_type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="base_variable_type"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;group ref="{http://ncei.noaa.gov/oads/v_a0_2_2}base_variable_elements"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "base_variable_type", propOrder = {
    "fullName",
    "datasetVarName",
    "variableType",
    "observationType",
    "units",
    "missingValue",
    "uncertainty",
    "qcFlag",
    "researcher",
    "methodReference",
    "calculationMethod",
    "manipulationMethod",
    "samplingInstrument",
    "analyzingInstrument",
    "detailedInfo",
    "fieldReplicateHandling",
    "standardization"
})
@XmlSeeAlso({
    DicVariableType.class,
    PhVariableType.class,
    Co2Base.class,
    BiologicalVariable.class
})
@SuperBuilder
@ToString
@NoArgsConstructor
@AllArgsConstructor
public class BaseVariableType implements Serializable
{

    private final static long serialVersionUID = 101L;
    @XmlElement(required = true)
    protected String fullName;
    @XmlElement(required = true)
    protected String datasetVarName;
    @XmlElement(required = true)
    protected String variableType;
    @XmlElement(required = true)
    protected String observationType;
    protected String units;
    protected String missingValue;
    protected String uncertainty;
    protected QcFlagInfoType qcFlag;
    @XmlElement(required = true)
    protected PersonReferenceType researcher;
    protected String methodReference;
    protected CalculationMethodType calculationMethod;
    protected String manipulationMethod;
    protected String samplingInstrument;
    protected String analyzingInstrument;
    protected String detailedInfo;
    protected String fieldReplicateHandling;
    protected StandardizationType standardization;
    @XmlAttribute(name = "name", required = true)
    protected String name;

    /**
     * Gets the value of the fullName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFullName() {
        return fullName;
    }

    /**
     * Sets the value of the fullName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFullName(String value) {
        this.fullName = value;
    }

    public boolean isSetFullName() {
        return (this.fullName!= null);
    }

    /**
     * Gets the value of the datasetVarName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDatasetVarName() {
        return datasetVarName;
    }

    /**
     * Sets the value of the datasetVarName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDatasetVarName(String value) {
        this.datasetVarName = value;
    }

    public boolean isSetDatasetVarName() {
        return (this.datasetVarName!= null);
    }

    /**
     * Gets the value of the variableType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVariableType() {
        return variableType;
    }

    /**
     * Sets the value of the variableType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVariableType(String value) {
        this.variableType = value;
    }

    public boolean isSetVariableType() {
        return (this.variableType!= null);
    }

    /**
     * Gets the value of the observationType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getObservationType() {
        return observationType;
    }

    /**
     * Sets the value of the observationType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setObservationType(String value) {
        this.observationType = value;
    }

    public boolean isSetObservationType() {
        return (this.observationType!= null);
    }

    /**
     * Gets the value of the units property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUnits() {
        return units;
    }

    /**
     * Sets the value of the units property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUnits(String value) {
        this.units = value;
    }

    public boolean isSetUnits() {
        return (this.units!= null);
    }

    /**
     * Gets the value of the missingValue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMissingValue() {
        return missingValue;
    }

    /**
     * Sets the value of the missingValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMissingValue(String value) {
        this.missingValue = value;
    }

    public boolean isSetMissingValue() {
        return (this.missingValue!= null);
    }

    /**
     * Gets the value of the uncertainty property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUncertainty() {
        return uncertainty;
    }

    /**
     * Sets the value of the uncertainty property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUncertainty(String value) {
        this.uncertainty = value;
    }

    public boolean isSetUncertainty() {
        return (this.uncertainty!= null);
    }

    /**
     * Gets the value of the qcFlag property.
     * 
     * @return
     *     possible object is
     *     {@link QcFlagInfoType }
     *     
     */
    public QcFlagInfoType getQcFlag() {
        return qcFlag;
    }

    /**
     * Sets the value of the qcFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link QcFlagInfoType }
     *     
     */
    public void setQcFlag(QcFlagInfoType value) {
        this.qcFlag = value;
    }

    public boolean isSetQcFlag() {
        return (this.qcFlag!= null);
    }

    /**
     * Gets the value of the researcher property.
     * 
     * @return
     *     possible object is
     *     {@link PersonReferenceType }
     *     
     */
    public PersonReferenceType getResearcher() {
        return researcher;
    }

    /**
     * Sets the value of the researcher property.
     * 
     * @param value
     *     allowed object is
     *     {@link PersonReferenceType }
     *     
     */
    public void setResearcher(PersonReferenceType value) {
        this.researcher = value;
    }

    public boolean isSetResearcher() {
        return (this.researcher!= null);
    }

    /**
     * Gets the value of the methodReference property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMethodReference() {
        return methodReference;
    }

    /**
     * Sets the value of the methodReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMethodReference(String value) {
        this.methodReference = value;
    }

    public boolean isSetMethodReference() {
        return (this.methodReference!= null);
    }

    /**
     * Gets the value of the calculationMethod property.
     * 
     * @return
     *     possible object is
     *     {@link CalculationMethodType }
     *     
     */
    public CalculationMethodType getCalculationMethod() {
        return calculationMethod;
    }

    /**
     * Sets the value of the calculationMethod property.
     * 
     * @param value
     *     allowed object is
     *     {@link CalculationMethodType }
     *     
     */
    public void setCalculationMethod(CalculationMethodType value) {
        this.calculationMethod = value;
    }

    public boolean isSetCalculationMethod() {
        return (this.calculationMethod!= null);
    }

    /**
     * Gets the value of the manipulationMethod property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getManipulationMethod() {
        return manipulationMethod;
    }

    /**
     * Sets the value of the manipulationMethod property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setManipulationMethod(String value) {
        this.manipulationMethod = value;
    }

    public boolean isSetManipulationMethod() {
        return (this.manipulationMethod!= null);
    }

    /**
     * Gets the value of the samplingInstrument property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSamplingInstrument() {
        return samplingInstrument;
    }

    /**
     * Sets the value of the samplingInstrument property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSamplingInstrument(String value) {
        this.samplingInstrument = value;
    }

    public boolean isSetSamplingInstrument() {
        return (this.samplingInstrument!= null);
    }

    /**
     * Gets the value of the analyzingInstrument property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAnalyzingInstrument() {
        return analyzingInstrument;
    }

    /**
     * Sets the value of the analyzingInstrument property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAnalyzingInstrument(String value) {
        this.analyzingInstrument = value;
    }

    public boolean isSetAnalyzingInstrument() {
        return (this.analyzingInstrument!= null);
    }

    /**
     * Gets the value of the detailedInfo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDetailedInfo() {
        return detailedInfo;
    }

    /**
     * Sets the value of the detailedInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDetailedInfo(String value) {
        this.detailedInfo = value;
    }

    public boolean isSetDetailedInfo() {
        return (this.detailedInfo!= null);
    }

    /**
     * Gets the value of the fieldReplicateHandling property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFieldReplicateHandling() {
        return fieldReplicateHandling;
    }

    /**
     * Sets the value of the fieldReplicateHandling property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFieldReplicateHandling(String value) {
        this.fieldReplicateHandling = value;
    }

    public boolean isSetFieldReplicateHandling() {
        return (this.fieldReplicateHandling!= null);
    }

    /**
     * Gets the value of the standardization property.
     * 
     * @return
     *     possible object is
     *     {@link StandardizationType }
     *     
     */
    public StandardizationType getStandardization() {
        return standardization;
    }

    /**
     * Sets the value of the standardization property.
     * 
     * @param value
     *     allowed object is
     *     {@link StandardizationType }
     *     
     */
    public void setStandardization(StandardizationType value) {
        this.standardization = value;
    }

    public boolean isSetStandardization() {
        return (this.standardization!= null);
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    public boolean isSetName() {
        return (this.name!= null);
    }

}
