//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.03.29 at 04:20:46 PM PDT 
//


package gov.noaa.ncei.oads.xml.v_a0_2_2;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;
import lombok.AllArgsConstructor;
import lombok.NoArgsConstructor;
import lombok.ToString;
import lombok.experimental.SuperBuilder;


/**
 * <p>Java class for co2_autonomous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="co2_autonomous"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://ncei.noaa.gov/oads/v_a0_2_2}co2_base"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="locationSeawaterIntake" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="depthSeawaterIntake" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="equilibrator" type="{http://ncei.noaa.gov/oads/v_a0_2_2}equilibrator_type" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "co2_autonomous", propOrder = {
    "locationSeawaterIntake",
    "depthSeawaterIntake",
    "equilibrator"
})
@SuperBuilder
@ToString
@NoArgsConstructor
@AllArgsConstructor
public class Co2Autonomous
    extends Co2Base
    implements Serializable
{

    private final static long serialVersionUID = 101L;
    protected String locationSeawaterIntake;
    protected String depthSeawaterIntake;
    protected EquilibratorType equilibrator;

    /**
     * Gets the value of the locationSeawaterIntake property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLocationSeawaterIntake() {
        return locationSeawaterIntake;
    }

    /**
     * Sets the value of the locationSeawaterIntake property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLocationSeawaterIntake(String value) {
        this.locationSeawaterIntake = value;
    }

    public boolean isSetLocationSeawaterIntake() {
        return (this.locationSeawaterIntake!= null);
    }

    /**
     * Gets the value of the depthSeawaterIntake property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDepthSeawaterIntake() {
        return depthSeawaterIntake;
    }

    /**
     * Sets the value of the depthSeawaterIntake property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDepthSeawaterIntake(String value) {
        this.depthSeawaterIntake = value;
    }

    public boolean isSetDepthSeawaterIntake() {
        return (this.depthSeawaterIntake!= null);
    }

    /**
     * Gets the value of the equilibrator property.
     * 
     * @return
     *     possible object is
     *     {@link EquilibratorType }
     *     
     */
    public EquilibratorType getEquilibrator() {
        return equilibrator;
    }

    /**
     * Sets the value of the equilibrator property.
     * 
     * @param value
     *     allowed object is
     *     {@link EquilibratorType }
     *     
     */
    public void setEquilibrator(EquilibratorType value) {
        this.equilibrator = value;
    }

    public boolean isSetEquilibrator() {
        return (this.equilibrator!= null);
    }

}
