//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.03.29 at 04:20:46 PM PDT 
//


package gov.noaa.ncei.oads.xml.v_a0_2_2;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;
import lombok.AllArgsConstructor;
import lombok.NoArgsConstructor;
import lombok.ToString;
import lombok.experimental.SuperBuilder;


/**
 * <p>Java class for co2_base complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="co2_base"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://ncei.noaa.gov/oads/v_a0_2_2}base_variable_type"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="gasDetector" type="{http://ncei.noaa.gov/oads/v_a0_2_2}gas_detector_type"/&gt;
 *         &lt;element name="waterVaporCorrection" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="temperatureCorrectionMethod" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="co2ReportTemperature" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "co2_base", propOrder = {
    "gasDetector",
    "waterVaporCorrection",
    "temperatureCorrectionMethod",
    "co2ReportTemperature"
})
@XmlSeeAlso({
    Co2Autonomous.class,
    Co2Discrete.class
})
@SuperBuilder
@ToString
@NoArgsConstructor
@AllArgsConstructor
public class Co2Base
    extends BaseVariableType
    implements Serializable
{

    private final static long serialVersionUID = 101L;
    @XmlElement(required = true)
    protected GasDetectorType gasDetector;
    @XmlElement(required = true)
    protected String waterVaporCorrection;
    @XmlElement(required = true)
    protected String temperatureCorrectionMethod;
    @XmlElement(required = true)
    protected String co2ReportTemperature;

    /**
     * Gets the value of the gasDetector property.
     * 
     * @return
     *     possible object is
     *     {@link GasDetectorType }
     *     
     */
    public GasDetectorType getGasDetector() {
        return gasDetector;
    }

    /**
     * Sets the value of the gasDetector property.
     * 
     * @param value
     *     allowed object is
     *     {@link GasDetectorType }
     *     
     */
    public void setGasDetector(GasDetectorType value) {
        this.gasDetector = value;
    }

    public boolean isSetGasDetector() {
        return (this.gasDetector!= null);
    }

    /**
     * Gets the value of the waterVaporCorrection property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWaterVaporCorrection() {
        return waterVaporCorrection;
    }

    /**
     * Sets the value of the waterVaporCorrection property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWaterVaporCorrection(String value) {
        this.waterVaporCorrection = value;
    }

    public boolean isSetWaterVaporCorrection() {
        return (this.waterVaporCorrection!= null);
    }

    /**
     * Gets the value of the temperatureCorrectionMethod property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTemperatureCorrectionMethod() {
        return temperatureCorrectionMethod;
    }

    /**
     * Sets the value of the temperatureCorrectionMethod property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTemperatureCorrectionMethod(String value) {
        this.temperatureCorrectionMethod = value;
    }

    public boolean isSetTemperatureCorrectionMethod() {
        return (this.temperatureCorrectionMethod!= null);
    }

    /**
     * Gets the value of the co2ReportTemperature property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCo2ReportTemperature() {
        return co2ReportTemperature;
    }

    /**
     * Sets the value of the co2ReportTemperature property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCo2ReportTemperature(String value) {
        this.co2ReportTemperature = value;
    }

    public boolean isSetCo2ReportTemperature() {
        return (this.co2ReportTemperature!= null);
    }

}
