//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.03.29 at 04:20:46 PM PDT 
//


package gov.noaa.ncei.oads.xml.v_a0_2_2;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import lombok.AllArgsConstructor;
import lombok.NoArgsConstructor;
import lombok.ToString;
import lombok.experimental.SuperBuilder;


/**
 * <p>Java class for co2_discrete complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="co2_discrete"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://ncei.noaa.gov/oads/v_a0_2_2}co2_base"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="storageMethod" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="seawaterVolume" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="headspaceVolume" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="measurementTemperature" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "co2_discrete", propOrder = {
    "storageMethod",
    "seawaterVolume",
    "headspaceVolume",
    "measurementTemperature"
})
@SuperBuilder
@ToString
@NoArgsConstructor
@AllArgsConstructor
public class Co2Discrete
    extends Co2Base
    implements Serializable
{

    private final static long serialVersionUID = 101L;
    @XmlElement(required = true)
    protected String storageMethod;
    @XmlElement(required = true)
    protected String seawaterVolume;
    @XmlElement(required = true)
    protected String headspaceVolume;
    @XmlElement(required = true)
    protected String measurementTemperature;

    /**
     * Gets the value of the storageMethod property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStorageMethod() {
        return storageMethod;
    }

    /**
     * Sets the value of the storageMethod property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStorageMethod(String value) {
        this.storageMethod = value;
    }

    public boolean isSetStorageMethod() {
        return (this.storageMethod!= null);
    }

    /**
     * Gets the value of the seawaterVolume property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSeawaterVolume() {
        return seawaterVolume;
    }

    /**
     * Sets the value of the seawaterVolume property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSeawaterVolume(String value) {
        this.seawaterVolume = value;
    }

    public boolean isSetSeawaterVolume() {
        return (this.seawaterVolume!= null);
    }

    /**
     * Gets the value of the headspaceVolume property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHeadspaceVolume() {
        return headspaceVolume;
    }

    /**
     * Sets the value of the headspaceVolume property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHeadspaceVolume(String value) {
        this.headspaceVolume = value;
    }

    public boolean isSetHeadspaceVolume() {
        return (this.headspaceVolume!= null);
    }

    /**
     * Gets the value of the measurementTemperature property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMeasurementTemperature() {
        return measurementTemperature;
    }

    /**
     * Sets the value of the measurementTemperature property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMeasurementTemperature(String value) {
        this.measurementTemperature = value;
    }

    public boolean isSetMeasurementTemperature() {
        return (this.measurementTemperature!= null);
    }

}
