//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.03.29 at 04:20:46 PM PDT 
//


package gov.noaa.ncei.oads.xml.v_a0_2_2;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.NoArgsConstructor;
import lombok.ToString;


/**
 * <p>Java class for crm_type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="crm_type"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="manufacturer" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="batch" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="bottle" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "crm_type", propOrder = {
    "manufacturer",
    "batch",
    "bottle"
})
@Builder
@ToString
@NoArgsConstructor
@AllArgsConstructor
public class CrmType implements Serializable
{

    private final static long serialVersionUID = 101L;
    @XmlElement(required = true)
    protected String manufacturer;
    @XmlElement(required = true)
    protected String batch;
    protected String bottle;

    /**
     * Gets the value of the manufacturer property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getManufacturer() {
        return manufacturer;
    }

    /**
     * Sets the value of the manufacturer property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setManufacturer(String value) {
        this.manufacturer = value;
    }

    public boolean isSetManufacturer() {
        return (this.manufacturer!= null);
    }

    /**
     * Gets the value of the batch property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBatch() {
        return batch;
    }

    /**
     * Sets the value of the batch property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBatch(String value) {
        this.batch = value;
    }

    public boolean isSetBatch() {
        return (this.batch!= null);
    }

    /**
     * Gets the value of the bottle property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBottle() {
        return bottle;
    }

    /**
     * Sets the value of the bottle property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBottle(String value) {
        this.bottle = value;
    }

    public boolean isSetBottle() {
        return (this.bottle!= null);
    }

}
