//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.03.29 at 04:20:46 PM PDT 
//


package gov.noaa.ncei.oads.xml.v_a0_2_2;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;
import lombok.AllArgsConstructor;
import lombok.NoArgsConstructor;
import lombok.ToString;
import lombok.experimental.SuperBuilder;


/**
 * <p>Java class for dic_variable_type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="dic_variable_type"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://ncei.noaa.gov/oads/v_a0_2_2}base_variable_type"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="poison" type="{http://ncei.noaa.gov/oads/v_a0_2_2}poison_type" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "dic_variable_type", propOrder = {
    "poison"
})
@XmlSeeAlso({
    TaVariableType.class
})
@SuperBuilder
@ToString
@NoArgsConstructor
@AllArgsConstructor
public class DicVariableType
    extends BaseVariableType
    implements Serializable
{

    private final static long serialVersionUID = 101L;
    protected PoisonType poison;

    /**
     * Gets the value of the poison property.
     * 
     * @return
     *     possible object is
     *     {@link PoisonType }
     *     
     */
    public PoisonType getPoison() {
        return poison;
    }

    /**
     * Sets the value of the poison property.
     * 
     * @param value
     *     allowed object is
     *     {@link PoisonType }
     *     
     */
    public void setPoison(PoisonType value) {
        this.poison = value;
    }

    public boolean isSetPoison() {
        return (this.poison!= null);
    }

}
