//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.03.29 at 04:20:46 PM PDT 
//


package gov.noaa.ncei.oads.xml.v_a0_2_2;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.NoArgsConstructor;
import lombok.ToString;


/**
 * <p>Java class for equilibrator_type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="equilibrator_type"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="type" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="volume" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="vented" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="waterFlowRate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="gasFlowRate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="temperatureMeasurement" type="{http://ncei.noaa.gov/oads/v_a0_2_2}equilibrator_sensor_type"/&gt;
 *         &lt;element name="pressureMeasurement" type="{http://ncei.noaa.gov/oads/v_a0_2_2}equilibrator_sensor_type"/&gt;
 *         &lt;element name="dryMethod" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "equilibrator_type", propOrder = {
    "type",
    "volume",
    "vented",
    "waterFlowRate",
    "gasFlowRate",
    "temperatureMeasurement",
    "pressureMeasurement",
    "dryMethod"
})
@Builder
@ToString
@NoArgsConstructor
@AllArgsConstructor
public class EquilibratorType implements Serializable
{

    private final static long serialVersionUID = 101L;
    protected String type;
    protected String volume;
    protected String vented;
    protected String waterFlowRate;
    protected String gasFlowRate;
    @XmlElement(required = true)
    protected EquilibratorSensorType temperatureMeasurement;
    @XmlElement(required = true)
    protected EquilibratorSensorType pressureMeasurement;
    protected String dryMethod;

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setType(String value) {
        this.type = value;
    }

    public boolean isSetType() {
        return (this.type!= null);
    }

    /**
     * Gets the value of the volume property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVolume() {
        return volume;
    }

    /**
     * Sets the value of the volume property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVolume(String value) {
        this.volume = value;
    }

    public boolean isSetVolume() {
        return (this.volume!= null);
    }

    /**
     * Gets the value of the vented property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVented() {
        return vented;
    }

    /**
     * Sets the value of the vented property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVented(String value) {
        this.vented = value;
    }

    public boolean isSetVented() {
        return (this.vented!= null);
    }

    /**
     * Gets the value of the waterFlowRate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWaterFlowRate() {
        return waterFlowRate;
    }

    /**
     * Sets the value of the waterFlowRate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWaterFlowRate(String value) {
        this.waterFlowRate = value;
    }

    public boolean isSetWaterFlowRate() {
        return (this.waterFlowRate!= null);
    }

    /**
     * Gets the value of the gasFlowRate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGasFlowRate() {
        return gasFlowRate;
    }

    /**
     * Sets the value of the gasFlowRate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGasFlowRate(String value) {
        this.gasFlowRate = value;
    }

    public boolean isSetGasFlowRate() {
        return (this.gasFlowRate!= null);
    }

    /**
     * Gets the value of the temperatureMeasurement property.
     * 
     * @return
     *     possible object is
     *     {@link EquilibratorSensorType }
     *     
     */
    public EquilibratorSensorType getTemperatureMeasurement() {
        return temperatureMeasurement;
    }

    /**
     * Sets the value of the temperatureMeasurement property.
     * 
     * @param value
     *     allowed object is
     *     {@link EquilibratorSensorType }
     *     
     */
    public void setTemperatureMeasurement(EquilibratorSensorType value) {
        this.temperatureMeasurement = value;
    }

    public boolean isSetTemperatureMeasurement() {
        return (this.temperatureMeasurement!= null);
    }

    /**
     * Gets the value of the pressureMeasurement property.
     * 
     * @return
     *     possible object is
     *     {@link EquilibratorSensorType }
     *     
     */
    public EquilibratorSensorType getPressureMeasurement() {
        return pressureMeasurement;
    }

    /**
     * Sets the value of the pressureMeasurement property.
     * 
     * @param value
     *     allowed object is
     *     {@link EquilibratorSensorType }
     *     
     */
    public void setPressureMeasurement(EquilibratorSensorType value) {
        this.pressureMeasurement = value;
    }

    public boolean isSetPressureMeasurement() {
        return (this.pressureMeasurement!= null);
    }

    /**
     * Gets the value of the dryMethod property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDryMethod() {
        return dryMethod;
    }

    /**
     * Sets the value of the dryMethod property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDryMethod(String value) {
        this.dryMethod = value;
    }

    public boolean isSetDryMethod() {
        return (this.dryMethod!= null);
    }

}
