//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.03.29 at 04:20:46 PM PDT 
//


package gov.noaa.ncei.oads.xml.v_a0_2_2;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.NoArgsConstructor;
import lombok.ToString;


/**
 * <p>Java class for equilibrator_sensor_type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="equilibrator_sensor_type"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="method" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="sensor"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="location" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="manufacturer" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="model" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="accuracy" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="precision" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="calibration" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="warming" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="comments" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "equilibrator_sensor_type", propOrder = {
    "method",
    "sensor",
    "comments"
})
@Builder
@ToString
@NoArgsConstructor
@AllArgsConstructor
public class EquilibratorSensorType implements Serializable
{

    private final static long serialVersionUID = 101L;
    @XmlElement(required = true)
    protected String method;
    @XmlElement(required = true)
    protected EquilibratorSensorType.Sensor sensor;
    @XmlElement(required = true)
    protected String comments;

    /**
     * Gets the value of the method property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMethod() {
        return method;
    }

    /**
     * Sets the value of the method property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMethod(String value) {
        this.method = value;
    }

    public boolean isSetMethod() {
        return (this.method!= null);
    }

    /**
     * Gets the value of the sensor property.
     * 
     * @return
     *     possible object is
     *     {@link EquilibratorSensorType.Sensor }
     *     
     */
    public EquilibratorSensorType.Sensor getSensor() {
        return sensor;
    }

    /**
     * Sets the value of the sensor property.
     * 
     * @param value
     *     allowed object is
     *     {@link EquilibratorSensorType.Sensor }
     *     
     */
    public void setSensor(EquilibratorSensorType.Sensor value) {
        this.sensor = value;
    }

    public boolean isSetSensor() {
        return (this.sensor!= null);
    }

    /**
     * Gets the value of the comments property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getComments() {
        return comments;
    }

    /**
     * Sets the value of the comments property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setComments(String value) {
        this.comments = value;
    }

    public boolean isSetComments() {
        return (this.comments!= null);
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="location" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="manufacturer" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="model" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="accuracy" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="precision" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="calibration" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="warming" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "location",
        "manufacturer",
        "model",
        "accuracy",
        "precision",
        "calibration",
        "warming"
    })
    public static class Sensor implements Serializable
    {

        private final static long serialVersionUID = 101L;
        @XmlElement(required = true)
        protected String location;
        @XmlElement(required = true)
        protected String manufacturer;
        @XmlElement(required = true)
        protected String model;
        @XmlElement(required = true)
        protected String accuracy;
        @XmlElement(required = true)
        protected String precision;
        @XmlElement(required = true)
        protected String calibration;
        @XmlElement(required = true)
        protected String warming;

        /**
         * Gets the value of the location property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLocation() {
            return location;
        }

        /**
         * Sets the value of the location property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLocation(String value) {
            this.location = value;
        }

        public boolean isSetLocation() {
            return (this.location!= null);
        }

        /**
         * Gets the value of the manufacturer property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getManufacturer() {
            return manufacturer;
        }

        /**
         * Sets the value of the manufacturer property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setManufacturer(String value) {
            this.manufacturer = value;
        }

        public boolean isSetManufacturer() {
            return (this.manufacturer!= null);
        }

        /**
         * Gets the value of the model property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getModel() {
            return model;
        }

        /**
         * Sets the value of the model property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setModel(String value) {
            this.model = value;
        }

        public boolean isSetModel() {
            return (this.model!= null);
        }

        /**
         * Gets the value of the accuracy property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAccuracy() {
            return accuracy;
        }

        /**
         * Sets the value of the accuracy property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAccuracy(String value) {
            this.accuracy = value;
        }

        public boolean isSetAccuracy() {
            return (this.accuracy!= null);
        }

        /**
         * Gets the value of the precision property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPrecision() {
            return precision;
        }

        /**
         * Sets the value of the precision property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPrecision(String value) {
            this.precision = value;
        }

        public boolean isSetPrecision() {
            return (this.precision!= null);
        }

        /**
         * Gets the value of the calibration property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCalibration() {
            return calibration;
        }

        /**
         * Sets the value of the calibration property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCalibration(String value) {
            this.calibration = value;
        }

        public boolean isSetCalibration() {
            return (this.calibration!= null);
        }

        /**
         * Gets the value of the warming property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getWarming() {
            return warming;
        }

        /**
         * Sets the value of the warming property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setWarming(String value) {
            this.warming = value;
        }

        public boolean isSetWarming() {
            return (this.warming!= null);
        }

    }

}
