//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.03.29 at 04:20:46 PM PDT 
//


package gov.noaa.ncei.oads.xml.v_a0_2_2;

import java.io.Serializable;
import java.util.Date;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementWrapper;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.NoArgsConstructor;
import lombok.Singular;
import lombok.ToString;
import org.w3._2001.xmlschema.Adapter1;


/**
 * <p>Java class for oads_metadata_document_type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="oads_metadata_document_type"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="submissionDate" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/&gt;
 *         &lt;element name="relatedDataSets" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="dataset" type="{http://ncei.noaa.gov/oads/v_a0_2_2}related_data_type" maxOccurs="unbounded"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="investigators"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="investigator" type="{http://ncei.noaa.gov/oads/v_a0_2_2}person_type" maxOccurs="unbounded"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="dataSubmitter" type="{http://ncei.noaa.gov/oads/v_a0_2_2}person_type"/&gt;
 *         &lt;element name="title" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="abstract" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="purpose" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="temporalExtents" type="{http://ncei.noaa.gov/oads/v_a0_2_2}temporal_extents_type"/&gt;
 *         &lt;element name="spatialExtents" type="{http://ncei.noaa.gov/oads/v_a0_2_2}spatial_extents_type"/&gt;
 *         &lt;element name="spatialReference" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="sampleCollectionRegions" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="region" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="organismCollectionRegions" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="region" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="fundingInfo" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="source" type="{http://ncei.noaa.gov/oads/v_a0_2_2}funding_source_type" maxOccurs="unbounded"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="researchProjects" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="project" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="platforms" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="platform" type="{http://ncei.noaa.gov/oads/v_a0_2_2}platform_type" maxOccurs="unbounded"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="expoCodes" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="expocode" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="cruiseIds" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="cruiseId" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="sections" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="section" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="authors"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="author" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="citation" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="references" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="reference" type="{http://ncei.noaa.gov/oads/v_a0_2_2}reference_type" maxOccurs="unbounded"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="supplementalInfo" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="keywords" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="keyword" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="variables" type="{http://ncei.noaa.gov/oads/v_a0_2_2}variable_collection"/&gt;
 *         &lt;element name="update" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="version" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "oads_metadata_document_type", propOrder = {
    "submissionDate",
    "relatedDataSets",
    "investigators",
    "dataSubmitter",
    "title",
    "_abstract",
    "purpose",
    "temporalExtents",
    "spatialExtents",
    "spatialReference",
    "sampleCollectionRegions",
    "organismCollectionRegions",
    "fundingInfo",
    "researchProjects",
    "platforms",
    "expoCodes",
    "cruiseIds",
    "sections",
    "authors",
    "citation",
    "references",
    "supplementalInfo",
    "keywords",
    "variables",
    "update"
})
@Builder
@ToString
@NoArgsConstructor
@AllArgsConstructor
public class OadsMetadataDocumentType implements Serializable
{

    private final static long serialVersionUID = 101L;
    @XmlElement(type = String.class)
    @XmlJavaTypeAdapter(Adapter1 .class)
    @XmlSchemaType(name = "date")
    protected Date submissionDate;
    @Singular("addRelated")
    @XmlElementWrapper
    @XmlElement(name = "dataset", namespace = "http://ncei.noaa.gov/oads/v_a0_2_2")
    protected List<RelatedDataType> relatedDataSets;
    @Singular("addInvestigator")
    @XmlElementWrapper(required = true)
    @XmlElement(name = "investigator", namespace = "http://ncei.noaa.gov/oads/v_a0_2_2")
    protected List<PersonType> investigators;
    @XmlElement(required = true)
    protected PersonType dataSubmitter;
    @XmlElement(required = true)
    protected String title;
    @XmlElement(name = "abstract", required = true)
    protected String _abstract;
    @XmlElement(required = true)
    protected String purpose;
    @XmlElement(required = true)
    protected TemporalExtentsType temporalExtents;
    @XmlElement(required = true)
    protected SpatialExtentsType spatialExtents;
    protected String spatialReference;
    @Singular("addSampleCollectionRegion")
    @XmlElementWrapper
    @XmlElement(name = "region", namespace = "http://ncei.noaa.gov/oads/v_a0_2_2")
    protected List<String> sampleCollectionRegions;
    @Singular("addOrganismCollectionRegion")
    @XmlElementWrapper
    @XmlElement(name = "region", namespace = "http://ncei.noaa.gov/oads/v_a0_2_2")
    protected List<String> organismCollectionRegions;
    @Singular("addFunding")
    @XmlElementWrapper
    @XmlElement(name = "source", namespace = "http://ncei.noaa.gov/oads/v_a0_2_2")
    protected List<FundingSourceType> fundingInfo;
    @Singular("addResearchProject")
    @XmlElementWrapper
    @XmlElement(name = "project", namespace = "http://ncei.noaa.gov/oads/v_a0_2_2")
    protected List<String> researchProjects;
    @Singular("addPlatform")
    @XmlElementWrapper
    @XmlElement(name = "platform", namespace = "http://ncei.noaa.gov/oads/v_a0_2_2")
    protected List<PlatformType> platforms;
    @Singular("addExpoCode")
    @XmlElementWrapper
    @XmlElement(name = "expocode", namespace = "http://ncei.noaa.gov/oads/v_a0_2_2")
    protected List<String> expoCodes;
    @Singular("addCruiseId")
    @XmlElementWrapper
    @XmlElement(name = "cruiseId", namespace = "http://ncei.noaa.gov/oads/v_a0_2_2")
    protected List<String> cruiseIds;
    @Singular("addSection")
    @XmlElementWrapper
    @XmlElement(name = "section", namespace = "http://ncei.noaa.gov/oads/v_a0_2_2")
    protected List<String> sections;
    @Singular("addAuthor")
    @XmlElementWrapper(required = true)
    @XmlElement(name = "author", namespace = "http://ncei.noaa.gov/oads/v_a0_2_2")
    protected List<String> authors;
    protected String citation;
    @Singular("addReference")
    @XmlElementWrapper
    @XmlElement(name = "reference", namespace = "http://ncei.noaa.gov/oads/v_a0_2_2")
    protected List<ReferenceType> references;
    protected String supplementalInfo;
    @Singular("addKeyword")
    @XmlElementWrapper
    @XmlElement(name = "keyword", namespace = "http://ncei.noaa.gov/oads/v_a0_2_2")
    protected List<String> keywords;
    @Singular("addVariable")
    @XmlElementWrapper(required = true)
    @XmlElements({
        @XmlElement(name = "variable", namespace = "http://ncei.noaa.gov/oads/v_a0_2_2"),
        @XmlElement(name = "dic", type = DicVariableType.class, namespace = "http://ncei.noaa.gov/oads/v_a0_2_2"),
        @XmlElement(name = "ta", type = TaVariableType.class, namespace = "http://ncei.noaa.gov/oads/v_a0_2_2"),
        @XmlElement(name = "ph", type = PhVariableType.class, namespace = "http://ncei.noaa.gov/oads/v_a0_2_2"),
        @XmlElement(name = "co2a", type = Co2Autonomous.class, namespace = "http://ncei.noaa.gov/oads/v_a0_2_2"),
        @XmlElement(name = "co2d", type = Co2Discrete.class, namespace = "http://ncei.noaa.gov/oads/v_a0_2_2")
    })
    protected List<BaseVariableType> variables;
    @XmlElement(type = String.class)
    @XmlJavaTypeAdapter(Adapter1 .class)
    @XmlSchemaType(name = "date")
    protected Date update;
    @XmlAttribute(name = "version", required = true)
    protected String version;

    /**
     * Gets the value of the submissionDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public Date getSubmissionDate() {
        return submissionDate;
    }

    /**
     * Sets the value of the submissionDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSubmissionDate(Date value) {
        this.submissionDate = value;
    }

    public boolean isSetSubmissionDate() {
        return (this.submissionDate!= null);
    }

    public boolean isSetRelatedDataSets() {
        return (this.relatedDataSets!= null);
    }

    public boolean isSetInvestigators() {
        return (this.investigators!= null);
    }

    /**
     * Gets the value of the dataSubmitter property.
     * 
     * @return
     *     possible object is
     *     {@link PersonType }
     *     
     */
    public PersonType getDataSubmitter() {
        return dataSubmitter;
    }

    /**
     * Sets the value of the dataSubmitter property.
     * 
     * @param value
     *     allowed object is
     *     {@link PersonType }
     *     
     */
    public void setDataSubmitter(PersonType value) {
        this.dataSubmitter = value;
    }

    public boolean isSetDataSubmitter() {
        return (this.dataSubmitter!= null);
    }

    /**
     * Gets the value of the title property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTitle() {
        return title;
    }

    /**
     * Sets the value of the title property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTitle(String value) {
        this.title = value;
    }

    public boolean isSetTitle() {
        return (this.title!= null);
    }

    /**
     * Gets the value of the abstract property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAbstract() {
        return _abstract;
    }

    /**
     * Sets the value of the abstract property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAbstract(String value) {
        this._abstract = value;
    }

    public boolean isSetAbstract() {
        return (this._abstract!= null);
    }

    /**
     * Gets the value of the purpose property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPurpose() {
        return purpose;
    }

    /**
     * Sets the value of the purpose property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPurpose(String value) {
        this.purpose = value;
    }

    public boolean isSetPurpose() {
        return (this.purpose!= null);
    }

    /**
     * Gets the value of the temporalExtents property.
     * 
     * @return
     *     possible object is
     *     {@link TemporalExtentsType }
     *     
     */
    public TemporalExtentsType getTemporalExtents() {
        return temporalExtents;
    }

    /**
     * Sets the value of the temporalExtents property.
     * 
     * @param value
     *     allowed object is
     *     {@link TemporalExtentsType }
     *     
     */
    public void setTemporalExtents(TemporalExtentsType value) {
        this.temporalExtents = value;
    }

    public boolean isSetTemporalExtents() {
        return (this.temporalExtents!= null);
    }

    /**
     * Gets the value of the spatialExtents property.
     * 
     * @return
     *     possible object is
     *     {@link SpatialExtentsType }
     *     
     */
    public SpatialExtentsType getSpatialExtents() {
        return spatialExtents;
    }

    /**
     * Sets the value of the spatialExtents property.
     * 
     * @param value
     *     allowed object is
     *     {@link SpatialExtentsType }
     *     
     */
    public void setSpatialExtents(SpatialExtentsType value) {
        this.spatialExtents = value;
    }

    public boolean isSetSpatialExtents() {
        return (this.spatialExtents!= null);
    }

    /**
     * Gets the value of the spatialReference property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSpatialReference() {
        return spatialReference;
    }

    /**
     * Sets the value of the spatialReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSpatialReference(String value) {
        this.spatialReference = value;
    }

    public boolean isSetSpatialReference() {
        return (this.spatialReference!= null);
    }

    public boolean isSetSampleCollectionRegions() {
        return (this.sampleCollectionRegions!= null);
    }

    public boolean isSetOrganismCollectionRegions() {
        return (this.organismCollectionRegions!= null);
    }

    public boolean isSetFundingInfo() {
        return (this.fundingInfo!= null);
    }

    public boolean isSetResearchProjects() {
        return (this.researchProjects!= null);
    }

    public boolean isSetPlatforms() {
        return (this.platforms!= null);
    }

    public boolean isSetExpoCodes() {
        return (this.expoCodes!= null);
    }

    public boolean isSetCruiseIds() {
        return (this.cruiseIds!= null);
    }

    public boolean isSetSections() {
        return (this.sections!= null);
    }

    public boolean isSetAuthors() {
        return (this.authors!= null);
    }

    /**
     * Gets the value of the citation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCitation() {
        return citation;
    }

    /**
     * Sets the value of the citation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCitation(String value) {
        this.citation = value;
    }

    public boolean isSetCitation() {
        return (this.citation!= null);
    }

    public boolean isSetReferences() {
        return (this.references!= null);
    }

    /**
     * Gets the value of the supplementalInfo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSupplementalInfo() {
        return supplementalInfo;
    }

    /**
     * Sets the value of the supplementalInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSupplementalInfo(String value) {
        this.supplementalInfo = value;
    }

    public boolean isSetSupplementalInfo() {
        return (this.supplementalInfo!= null);
    }

    public boolean isSetKeywords() {
        return (this.keywords!= null);
    }

    public boolean isSetVariables() {
        return (this.variables!= null);
    }

    /**
     * Gets the value of the update property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public Date getUpdate() {
        return update;
    }

    /**
     * Sets the value of the update property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUpdate(Date value) {
        this.update = value;
    }

    public boolean isSetUpdate() {
        return (this.update!= null);
    }

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVersion() {
        return version;
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVersion(String value) {
        this.version = value;
    }

    public boolean isSetVersion() {
        return (this.version!= null);
    }

    public List<RelatedDataType> getRelatedDataSets() {
        return relatedDataSets;
    }

    public void setRelatedDataSets(List<RelatedDataType> relatedDataSets) {
        this.relatedDataSets = relatedDataSets;
    }

    public List<PersonType> getInvestigators() {
        return investigators;
    }

    public void setInvestigators(List<PersonType> investigators) {
        this.investigators = investigators;
    }

    public List<String> getSampleCollectionRegions() {
        return sampleCollectionRegions;
    }

    public void setSampleCollectionRegions(List<String> sampleCollectionRegions) {
        this.sampleCollectionRegions = sampleCollectionRegions;
    }

    public List<String> getOrganismCollectionRegions() {
        return organismCollectionRegions;
    }

    public void setOrganismCollectionRegions(List<String> organismCollectionRegions) {
        this.organismCollectionRegions = organismCollectionRegions;
    }

    public List<FundingSourceType> getFundingInfo() {
        return fundingInfo;
    }

    public void setFundingInfo(List<FundingSourceType> fundingInfo) {
        this.fundingInfo = fundingInfo;
    }

    public List<String> getResearchProjects() {
        return researchProjects;
    }

    public void setResearchProjects(List<String> researchProjects) {
        this.researchProjects = researchProjects;
    }

    public List<PlatformType> getPlatforms() {
        return platforms;
    }

    public void setPlatforms(List<PlatformType> platforms) {
        this.platforms = platforms;
    }

    public List<String> getExpoCodes() {
        return expoCodes;
    }

    public void setExpoCodes(List<String> expoCodes) {
        this.expoCodes = expoCodes;
    }

    public List<String> getCruiseIds() {
        return cruiseIds;
    }

    public void setCruiseIds(List<String> cruiseIds) {
        this.cruiseIds = cruiseIds;
    }

    public List<String> getSections() {
        return sections;
    }

    public void setSections(List<String> sections) {
        this.sections = sections;
    }

    public List<String> getAuthors() {
        return authors;
    }

    public void setAuthors(List<String> authors) {
        this.authors = authors;
    }

    public List<ReferenceType> getReferences() {
        return references;
    }

    public void setReferences(List<ReferenceType> references) {
        this.references = references;
    }

    public List<String> getKeywords() {
        return keywords;
    }

    public void setKeywords(List<String> keywords) {
        this.keywords = keywords;
    }

    public List<BaseVariableType> getVariables() {
        return variables;
    }

    public void setVariables(List<BaseVariableType> variables) {
        this.variables = variables;
    }
    
        
    public void clearEmptyCollections() {
        System.out.println("Clearing empty collections.");
        if ( relatedDataSets != null && relatedDataSets.isEmpty()) { relatedDataSets = null; }
		if ( investigators != null && investigators.isEmpty()) { investigators = null; }
		if ( sampleCollectionRegions != null && sampleCollectionRegions.isEmpty()) { sampleCollectionRegions = null; }
		if ( organismCollectionRegions != null && organismCollectionRegions.isEmpty()) { organismCollectionRegions = null; }
		if ( fundingInfo != null && fundingInfo.isEmpty()) { fundingInfo = null; }
		if ( researchProjects != null && researchProjects.isEmpty()) { researchProjects = null; }
		if ( platforms != null && platforms.isEmpty()) { platforms = null; }
		if ( expoCodes != null && expoCodes.isEmpty()) { expoCodes = null; }
		if ( cruiseIds != null && cruiseIds.isEmpty()) { cruiseIds = null; }
		if ( sections != null && sections.isEmpty()) { sections = null; }
		if ( authors != null && authors.isEmpty()) { authors = null; }
		if ( references != null && references.isEmpty()) { references = null; }
		if ( keywords != null && keywords.isEmpty()) { keywords = null; }
		if ( variables != null && variables.isEmpty()) { variables = null; }
    }
        
        
}
