//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.03.29 at 04:20:46 PM PDT 
//


package gov.noaa.ncei.oads.xml.v_a0_2_2;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the gov.noaa.ncei.oads.xml.v_a0_2_2 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _OadsMetadata_QNAME = new QName("http://ncei.noaa.gov/oads/v_a0_2_2", "oads_metadata");
    private final static QName _AbstractString_QNAME = new QName("http://ncei.noaa.gov/oads/v_a0_2_2", "abstract_string");
    private final static QName _Author_QNAME = new QName("http://ncei.noaa.gov/oads/v_a0_2_2", "author");
    private final static QName _Reference_QNAME = new QName("http://ncei.noaa.gov/oads/v_a0_2_2", "reference");
    private final static QName _Keyword_QNAME = new QName("http://ncei.noaa.gov/oads/v_a0_2_2", "keyword");
    private final static QName _Code_QNAME = new QName("http://ncei.noaa.gov/oads/v_a0_2_2", "code");
    private final static QName _Id_QNAME = new QName("http://ncei.noaa.gov/oads/v_a0_2_2", "id");
    private final static QName _Expocode_QNAME = new QName("http://ncei.noaa.gov/oads/v_a0_2_2", "expocode");
    private final static QName _CruiseId_QNAME = new QName("http://ncei.noaa.gov/oads/v_a0_2_2", "cruiseId");
    private final static QName _Section_QNAME = new QName("http://ncei.noaa.gov/oads/v_a0_2_2", "section");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: gov.noaa.ncei.oads.xml.v_a0_2_2
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link EquilibratorSensorType }
     * 
     */
    public EquilibratorSensorType createEquilibratorSensorType() {
        return new EquilibratorSensorType();
    }

    /**
     * Create an instance of {@link OadsMetadataDocumentType }
     * 
     */
    public OadsMetadataDocumentType createOadsMetadataDocumentType() {
        return new OadsMetadataDocumentType();
    }

    /**
     * Create an instance of {@link OrderedStringElementType }
     * 
     */
    public OrderedStringElementType createOrderedStringElementType() {
        return new OrderedStringElementType();
    }

    /**
     * Create an instance of {@link TypedElementType }
     * 
     */
    public TypedElementType createTypedElementType() {
        return new TypedElementType();
    }

    /**
     * Create an instance of {@link TypedStringType }
     * 
     */
    public TypedStringType createTypedStringType() {
        return new TypedStringType();
    }

    /**
     * Create an instance of {@link ValueWithUnitType }
     * 
     */
    public ValueWithUnitType createValueWithUnitType() {
        return new ValueWithUnitType();
    }

    /**
     * Create an instance of {@link TypedIdentifierType }
     * 
     */
    public TypedIdentifierType createTypedIdentifierType() {
        return new TypedIdentifierType();
    }

    /**
     * Create an instance of {@link PersonType }
     * 
     */
    public PersonType createPersonType() {
        return new PersonType();
    }

    /**
     * Create an instance of {@link PersonNameType }
     * 
     */
    public PersonNameType createPersonNameType() {
        return new PersonNameType();
    }

    /**
     * Create an instance of {@link PersonContactInfoType }
     * 
     */
    public PersonContactInfoType createPersonContactInfoType() {
        return new PersonContactInfoType();
    }

    /**
     * Create an instance of {@link AddressType }
     * 
     */
    public AddressType createAddressType() {
        return new AddressType();
    }

    /**
     * Create an instance of {@link PersonReferenceType }
     * 
     */
    public PersonReferenceType createPersonReferenceType() {
        return new PersonReferenceType();
    }

    /**
     * Create an instance of {@link BaseVariableType }
     * 
     */
    public BaseVariableType createBaseVariableType() {
        return new BaseVariableType();
    }

    /**
     * Create an instance of {@link DicVariableType }
     * 
     */
    public DicVariableType createDicVariableType() {
        return new DicVariableType();
    }

    /**
     * Create an instance of {@link TaVariableType }
     * 
     */
    public TaVariableType createTaVariableType() {
        return new TaVariableType();
    }

    /**
     * Create an instance of {@link PhVariableType }
     * 
     */
    public PhVariableType createPhVariableType() {
        return new PhVariableType();
    }

    /**
     * Create an instance of {@link Co2Base }
     * 
     */
    public Co2Base createCo2Base() {
        return new Co2Base();
    }

    /**
     * Create an instance of {@link Co2Autonomous }
     * 
     */
    public Co2Autonomous createCo2Autonomous() {
        return new Co2Autonomous();
    }

    /**
     * Create an instance of {@link Co2Discrete }
     * 
     */
    public Co2Discrete createCo2Discrete() {
        return new Co2Discrete();
    }

    /**
     * Create an instance of {@link BiologicalVariable }
     * 
     */
    public BiologicalVariable createBiologicalVariable() {
        return new BiologicalVariable();
    }

    /**
     * Create an instance of {@link QcFlagInfoType }
     * 
     */
    public QcFlagInfoType createQcFlagInfoType() {
        return new QcFlagInfoType();
    }

    /**
     * Create an instance of {@link EquilibratorType }
     * 
     */
    public EquilibratorType createEquilibratorType() {
        return new EquilibratorType();
    }

    /**
     * Create an instance of {@link GasDetectorType }
     * 
     */
    public GasDetectorType createGasDetectorType() {
        return new GasDetectorType();
    }

    /**
     * Create an instance of {@link StandardizationType }
     * 
     */
    public StandardizationType createStandardizationType() {
        return new StandardizationType();
    }

    /**
     * Create an instance of {@link CrmType }
     * 
     */
    public CrmType createCrmType() {
        return new CrmType();
    }

    /**
     * Create an instance of {@link StandardGasType }
     * 
     */
    public StandardGasType createStandardGasType() {
        return new StandardGasType();
    }

    /**
     * Create an instance of {@link PoisonType }
     * 
     */
    public PoisonType createPoisonType() {
        return new PoisonType();
    }

    /**
     * Create an instance of {@link CalculationMethodType }
     * 
     */
    public CalculationMethodType createCalculationMethodType() {
        return new CalculationMethodType();
    }

    /**
     * Create an instance of {@link CalculationParameterType }
     * 
     */
    public CalculationParameterType createCalculationParameterType() {
        return new CalculationParameterType();
    }

    /**
     * Create an instance of {@link ArchiveInfoType }
     * 
     */
    public ArchiveInfoType createArchiveInfoType() {
        return new ArchiveInfoType();
    }

    /**
     * Create an instance of {@link RelatedDataType }
     * 
     */
    public RelatedDataType createRelatedDataType() {
        return new RelatedDataType();
    }

    /**
     * Create an instance of {@link TemporalExtentsType }
     * 
     */
    public TemporalExtentsType createTemporalExtentsType() {
        return new TemporalExtentsType();
    }

    /**
     * Create an instance of {@link SpatialExtentsType }
     * 
     */
    public SpatialExtentsType createSpatialExtentsType() {
        return new SpatialExtentsType();
    }

    /**
     * Create an instance of {@link AltitudeRangeType }
     * 
     */
    public AltitudeRangeType createAltitudeRangeType() {
        return new AltitudeRangeType();
    }

    /**
     * Create an instance of {@link DepthRangeType }
     * 
     */
    public DepthRangeType createDepthRangeType() {
        return new DepthRangeType();
    }

    /**
     * Create an instance of {@link FundingSourceType }
     * 
     */
    public FundingSourceType createFundingSourceType() {
        return new FundingSourceType();
    }

    /**
     * Create an instance of {@link PlatformType }
     * 
     */
    public PlatformType createPlatformType() {
        return new PlatformType();
    }

    /**
     * Create an instance of {@link ReferenceType }
     * 
     */
    public ReferenceType createReferenceType() {
        return new ReferenceType();
    }

    /**
     * Create an instance of {@link GeneralStringCollection }
     * 
     */
    public GeneralStringCollection createGeneralStringCollection() {
        return new GeneralStringCollection();
    }

    /**
     * Create an instance of {@link EquilibratorSensorType.Sensor }
     * 
     */
    public EquilibratorSensorType.Sensor createEquilibratorSensorTypeSensor() {
        return new EquilibratorSensorType.Sensor();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OadsMetadataDocumentType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link OadsMetadataDocumentType }{@code >}
     */
    @XmlElementDecl(namespace = "http://ncei.noaa.gov/oads/v_a0_2_2", name = "oads_metadata")
    public JAXBElement<OadsMetadataDocumentType> createOadsMetadata(OadsMetadataDocumentType value) {
        return new JAXBElement<OadsMetadataDocumentType>(_OadsMetadata_QNAME, OadsMetadataDocumentType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://ncei.noaa.gov/oads/v_a0_2_2", name = "abstract_string")
    public JAXBElement<String> createAbstractString(String value) {
        return new JAXBElement<String>(_AbstractString_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://ncei.noaa.gov/oads/v_a0_2_2", name = "author", substitutionHeadNamespace = "http://ncei.noaa.gov/oads/v_a0_2_2", substitutionHeadName = "abstract_string")
    public JAXBElement<String> createAuthor(String value) {
        return new JAXBElement<String>(_Author_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://ncei.noaa.gov/oads/v_a0_2_2", name = "reference", substitutionHeadNamespace = "http://ncei.noaa.gov/oads/v_a0_2_2", substitutionHeadName = "abstract_string")
    public JAXBElement<String> createReference(String value) {
        return new JAXBElement<String>(_Reference_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://ncei.noaa.gov/oads/v_a0_2_2", name = "keyword", substitutionHeadNamespace = "http://ncei.noaa.gov/oads/v_a0_2_2", substitutionHeadName = "abstract_string")
    public JAXBElement<String> createKeyword(String value) {
        return new JAXBElement<String>(_Keyword_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://ncei.noaa.gov/oads/v_a0_2_2", name = "code", substitutionHeadNamespace = "http://ncei.noaa.gov/oads/v_a0_2_2", substitutionHeadName = "abstract_string")
    public JAXBElement<String> createCode(String value) {
        return new JAXBElement<String>(_Code_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://ncei.noaa.gov/oads/v_a0_2_2", name = "id", substitutionHeadNamespace = "http://ncei.noaa.gov/oads/v_a0_2_2", substitutionHeadName = "abstract_string")
    public JAXBElement<String> createId(String value) {
        return new JAXBElement<String>(_Id_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://ncei.noaa.gov/oads/v_a0_2_2", name = "expocode", substitutionHeadNamespace = "http://ncei.noaa.gov/oads/v_a0_2_2", substitutionHeadName = "abstract_string")
    public JAXBElement<String> createExpocode(String value) {
        return new JAXBElement<String>(_Expocode_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://ncei.noaa.gov/oads/v_a0_2_2", name = "cruiseId", substitutionHeadNamespace = "http://ncei.noaa.gov/oads/v_a0_2_2", substitutionHeadName = "abstract_string")
    public JAXBElement<String> createCruiseId(String value) {
        return new JAXBElement<String>(_CruiseId_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://ncei.noaa.gov/oads/v_a0_2_2", name = "section", substitutionHeadNamespace = "http://ncei.noaa.gov/oads/v_a0_2_2", substitutionHeadName = "abstract_string")
    public JAXBElement<String> createSection(String value) {
        return new JAXBElement<String>(_Section_QNAME, String.class, null, value);
    }

}
