//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.03.29 at 04:20:46 PM PDT 
//


package gov.noaa.ncei.oads.xml.v_a0_2_2;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for observation_type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="observation_type"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="Point"/&gt;
 *     &lt;enumeration value="Timeseries"/&gt;
 *     &lt;enumeration value="Trajectory"/&gt;
 *     &lt;enumeration value="Profile"/&gt;
 *     &lt;enumeration value="Timeseries_Profile"/&gt;
 *     &lt;enumeration value="Trajectory_Profile"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "observation_type")
@XmlEnum
public enum ObservationType {

    @XmlEnumValue("Point")
    POINT("Point"),
    @XmlEnumValue("Timeseries")
    TIMESERIES("Timeseries"),
    @XmlEnumValue("Trajectory")
    TRAJECTORY("Trajectory"),
    @XmlEnumValue("Profile")
    PROFILE("Profile"),
    @XmlEnumValue("Timeseries_Profile")
    TIMESERIES_PROFILE("Timeseries_Profile"),
    @XmlEnumValue("Trajectory_Profile")
    TRAJECTORY_PROFILE("Trajectory_Profile");
    private final String value;

    ObservationType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static ObservationType fromValue(String v) {
        for (ObservationType c: ObservationType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
