//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.03.29 at 04:20:46 PM PDT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://ncei.noaa.gov/oads/v_a0_2_2", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package gov.noaa.ncei.oads.xml.v_a0_2_2;
