//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.03.29 at 04:20:46 PM PDT 
//


package gov.noaa.ncei.oads.xml.v_a0_2_2;

import java.io.Serializable;
import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.NoArgsConstructor;
import lombok.ToString;


/**
 * <p>Java class for spatial_extents_type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="spatial_extents_type"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="westernBounds" type="{http://www.w3.org/2001/XMLSchema}decimal"/&gt;
 *         &lt;element name="easternBounds" type="{http://www.w3.org/2001/XMLSchema}decimal"/&gt;
 *         &lt;element name="northernBounds" type="{http://www.w3.org/2001/XMLSchema}decimal"/&gt;
 *         &lt;element name="southernBounds" type="{http://www.w3.org/2001/XMLSchema}decimal"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "spatial_extents_type", propOrder = {
    "westernBounds",
    "easternBounds",
    "northernBounds",
    "southernBounds"
})
@Builder
@ToString
@NoArgsConstructor
@AllArgsConstructor
public class SpatialExtentsType implements Serializable
{

    private final static long serialVersionUID = 101L;
    @XmlElement(required = true)
    protected BigDecimal westernBounds;
    @XmlElement(required = true)
    protected BigDecimal easternBounds;
    @XmlElement(required = true)
    protected BigDecimal northernBounds;
    @XmlElement(required = true)
    protected BigDecimal southernBounds;

    /**
     * Gets the value of the westernBounds property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getWesternBounds() {
        return westernBounds;
    }

    /**
     * Sets the value of the westernBounds property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setWesternBounds(BigDecimal value) {
        this.westernBounds = value;
    }

    public boolean isSetWesternBounds() {
        return (this.westernBounds!= null);
    }

    /**
     * Gets the value of the easternBounds property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getEasternBounds() {
        return easternBounds;
    }

    /**
     * Sets the value of the easternBounds property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setEasternBounds(BigDecimal value) {
        this.easternBounds = value;
    }

    public boolean isSetEasternBounds() {
        return (this.easternBounds!= null);
    }

    /**
     * Gets the value of the northernBounds property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getNorthernBounds() {
        return northernBounds;
    }

    /**
     * Sets the value of the northernBounds property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setNorthernBounds(BigDecimal value) {
        this.northernBounds = value;
    }

    public boolean isSetNorthernBounds() {
        return (this.northernBounds!= null);
    }

    /**
     * Gets the value of the southernBounds property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getSouthernBounds() {
        return southernBounds;
    }

    /**
     * Sets the value of the southernBounds property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setSouthernBounds(BigDecimal value) {
        this.southernBounds = value;
    }

    public boolean isSetSouthernBounds() {
        return (this.southernBounds!= null);
    }

}
