//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.03.29 at 04:20:46 PM PDT 
//


package gov.noaa.ncei.oads.xml.v_a0_2_2;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.NoArgsConstructor;
import lombok.Singular;
import lombok.ToString;


/**
 * <p>Java class for standardization_type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="standardization_type"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="frequency" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="temperature" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *         &lt;choice&gt;
 *           &lt;sequence&gt;
 *             &lt;element name="standardGas" type="{http://ncei.noaa.gov/oads/v_a0_2_2}standard_gas_type" maxOccurs="unbounded" minOccurs="0"/&gt;
 *             &lt;element name="crm" type="{http://ncei.noaa.gov/oads/v_a0_2_2}crm_type" minOccurs="0"/&gt;
 *           &lt;/sequence&gt;
 *           &lt;element name="phOfStandards" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;/choice&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "standardization_type", propOrder = {
    "description",
    "frequency",
    "temperature",
    "standardGas",
    "crm",
    "phOfStandards"
})
@Builder(toBuilder = true)
@ToString
@NoArgsConstructor
@AllArgsConstructor
public class StandardizationType implements Serializable
{

    private final static long serialVersionUID = 101L;
    @XmlElement(required = true)
    protected String description;
    @XmlElement(required = true)
    protected String frequency;
    protected BigDecimal temperature;
    @Singular("addStandardGas")
    protected List<StandardGasType> standardGas;
    protected CrmType crm;
    protected String phOfStandards;

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    public boolean isSetDescription() {
        return (this.description!= null);
    }

    /**
     * Gets the value of the frequency property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFrequency() {
        return frequency;
    }

    /**
     * Sets the value of the frequency property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFrequency(String value) {
        this.frequency = value;
    }

    public boolean isSetFrequency() {
        return (this.frequency!= null);
    }

    /**
     * Gets the value of the temperature property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTemperature() {
        return temperature;
    }

    /**
     * Sets the value of the temperature property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setTemperature(BigDecimal value) {
        this.temperature = value;
    }

    public boolean isSetTemperature() {
        return (this.temperature!= null);
    }

    /**
     * Gets the value of the standardGas property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the standardGas property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getStandardGas().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link StandardGasType }
     * 
     * 
     */
    public List<StandardGasType> getStandardGas() {
        if (standardGas == null) {
            standardGas = new ArrayList<StandardGasType>();
        }
        return this.standardGas;
    }

    public boolean isSetStandardGas() {
        return ((this.standardGas!= null)&&(!this.standardGas.isEmpty()));
    }

    public void unsetStandardGas() {
        this.standardGas = null;
    }

    /**
     * Gets the value of the crm property.
     * 
     * @return
     *     possible object is
     *     {@link CrmType }
     *     
     */
    public CrmType getCrm() {
        return crm;
    }

    /**
     * Sets the value of the crm property.
     * 
     * @param value
     *     allowed object is
     *     {@link CrmType }
     *     
     */
    public void setCrm(CrmType value) {
        this.crm = value;
    }

    public boolean isSetCrm() {
        return (this.crm!= null);
    }

    /**
     * Gets the value of the phOfStandards property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPhOfStandards() {
        return phOfStandards;
    }

    /**
     * Sets the value of the phOfStandards property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPhOfStandards(String value) {
        this.phOfStandards = value;
    }

    public boolean isSetPhOfStandards() {
        return (this.phOfStandards!= null);
    }

}
