//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.03.29 at 04:20:46 PM PDT 
//


package gov.noaa.ncei.oads.xml.v_a0_2_2;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import lombok.AllArgsConstructor;
import lombok.NoArgsConstructor;
import lombok.ToString;
import lombok.experimental.SuperBuilder;


/**
 * <p>Java class for ta_variable_type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ta_variable_type"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://ncei.noaa.gov/oads/v_a0_2_2}dic_variable_type"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="titrationType" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="cellType" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="curveFitting" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="blankCorrection" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ta_variable_type", propOrder = {
    "titrationType",
    "cellType",
    "curveFitting",
    "blankCorrection"
})
@SuperBuilder
@ToString
@NoArgsConstructor
@AllArgsConstructor
public class TaVariableType
    extends DicVariableType
    implements Serializable
{

    private final static long serialVersionUID = 101L;
    @XmlElement(required = true)
    protected String titrationType;
    @XmlElement(required = true)
    protected String cellType;
    @XmlElement(required = true)
    protected String curveFitting;
    protected String blankCorrection;

    /**
     * Gets the value of the titrationType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTitrationType() {
        return titrationType;
    }

    /**
     * Sets the value of the titrationType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTitrationType(String value) {
        this.titrationType = value;
    }

    public boolean isSetTitrationType() {
        return (this.titrationType!= null);
    }

    /**
     * Gets the value of the cellType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCellType() {
        return cellType;
    }

    /**
     * Sets the value of the cellType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCellType(String value) {
        this.cellType = value;
    }

    public boolean isSetCellType() {
        return (this.cellType!= null);
    }

    /**
     * Gets the value of the curveFitting property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCurveFitting() {
        return curveFitting;
    }

    /**
     * Sets the value of the curveFitting property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCurveFitting(String value) {
        this.curveFitting = value;
    }

    public boolean isSetCurveFitting() {
        return (this.curveFitting!= null);
    }

    /**
     * Gets the value of the blankCorrection property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBlankCorrection() {
        return blankCorrection;
    }

    /**
     * Sets the value of the blankCorrection property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBlankCorrection(String value) {
        this.blankCorrection = value;
    }

    public boolean isSetBlankCorrection() {
        return (this.blankCorrection!= null);
    }

}
