//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.03.29 at 04:20:46 PM PDT 
//


package gov.noaa.ncei.oads.xml.v_a0_2_2;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for variable_type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="variable_type"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="UNSPECIFIED"/&gt;
 *     &lt;enumeration value="IN_SITU"/&gt;
 *     &lt;enumeration value="DISCRETE"/&gt;
 *     &lt;enumeration value="COMPUTED"/&gt;
 *     &lt;enumeration value="EXPERIMENT"/&gt;
 *     &lt;enumeration value="MANIPULATION"/&gt;
 *     &lt;enumeration value="RESPONSE"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "variable_type")
@XmlEnum
public enum VariableType {

    UNSPECIFIED,
    IN_SITU,
    DISCRETE,
    COMPUTED,
    EXPERIMENT,
    MANIPULATION,
    RESPONSE;

    public String value() {
        return name();
    }

    public static VariableType fromValue(String v) {
        return valueOf(v);
    }

}
